using System;
using System.Collections.Generic;

namespace TweekPro.Tracks {
 /// <summary>English strings for the Privacy Tracks tab; merged by Core.L (keys must not repeat in other tables).</summary>
 public static class TracksLang {
  public static readonly Dictionary<string,string> Table=new Dictionary<string,string>(StringComparer.Ordinal){
   {"Dấu vết","Tracks"},{"Số mục","Items"},{"Chọn mặc định","Select defaults"},{"Dọn dấu vết đã chọn (vào kho)","Clean selected tracks (to vault)"},{"Đang xem trước…","Previewing…"},
   {"Tệp mở gần đây (Recent)","Recently opened files (Recent)"},{"Shortcut tới tệp và thư mục vừa mở; Explorer và hộp Mở/Lưu dùng để gợi ý.","Shortcuts to files and folders you just opened; Explorer and Open/Save dialogs use them for suggestions."},
   {"Jump List trên thanh tác vụ","Taskbar Jump Lists"},{"Danh sách «gần đây / thường dùng» khi chuột phải biểu tượng trên taskbar và Start.","The \"recent / frequent\" lists shown when right-clicking taskbar and Start icons."},
   {"Lịch sử hoạt động (Timeline)","Activity history (Timeline)"},{"Cơ sở dữ liệu ActivitiesCache.db của Timeline / Đồng bộ hoạt động; tệp đang được dịch vụ giữ sẽ bị bỏ qua.","The ActivitiesCache.db database behind Timeline / activity sync; files held by the service are skipped."},
   {"Lịch sử hộp Run (Win+R)","Run dialog history (Win+R)"},{"Các lệnh đã gõ vào hộp Run.","Commands typed into the Run box."},
   {"Đường dẫn đã gõ vào thanh địa chỉ","Paths typed into the address bar"},{"Đường dẫn gõ vào thanh địa chỉ Explorer.","Paths typed into the Explorer address bar."},
   {"RecentDocs (tài liệu theo đuôi tệp)","RecentDocs (documents by extension)"},{"Tên tệp vừa mở, xếp theo phần mở rộng; nguồn của menu «Recent» trong Start.","Names of files just opened, grouped by extension; feeds the Start \"Recent\" menu."},
   {"Hộp Mở / Lưu (ComDlg32)","Open / Save dialogs (ComDlg32)"},{"Tệp và thư mục dùng gần đây trong hộp thoại Mở/Lưu của mọi ứng dụng.","Files and folders recently used in every application's Open/Save dialog."},
   {"Từ khóa tìm trong Explorer","Explorer search terms"},{"Chuỗi đã gõ vào ô tìm kiếm của Explorer (WordWheelQuery).","Strings typed into the Explorer search box (WordWheelQuery)."},
   {"Thống kê chạy chương trình (UserAssist)","Program launch statistics (UserAssist)"},{"Số lần và lần cuối chạy từng chương trình từ Start; Start dùng để xếp «Most used».","Launch count and last run of each program from Start; Start uses it for \"Most used\"."},
   {"Tệp gần đây của Paint, WordPad","Recent files of Paint, WordPad"},{"Danh sách tệp gần đây của Paint và WordPad.","Recent file lists of Paint and WordPad."},
   {"Khóa mở lần cuối của Regedit","Last key opened in Regedit"},{"Giá trị LastKey của Regedit; Favorites (dấu trang Registry) được giữ nguyên.","Regedit's LastKey value; Favorites (registry bookmarks) are kept."},
   {"Lịch sử lệnh PowerShell","PowerShell command history"},{"ConsoleHost_history.txt của PSReadLine: mọi lệnh đã gõ trong PowerShell và Windows Terminal.","PSReadLine's ConsoleHost_history.txt: every command typed in PowerShell and Windows Terminal."},
   {"Máy Remote Desktop đã kết nối","Remote Desktop connections"},{"Danh sách máy và tên đăng nhập gợi ý của Remote Desktop Connection (mstsc).","Hosts and suggested user names remembered by Remote Desktop Connection (mstsc)."},
   {"Ổ mạng đã ánh xạ gần đây","Recently mapped network drives"},{"Đường dẫn UNC đã gõ vào hộp Map Network Drive.","UNC paths typed into the Map Network Drive dialog."},
   {"Ứng dụng gần đây của Search / Start","Recent apps of Search / Start"},{"Ứng dụng và tệp mở gần đây mà Windows Search ghi lại để gợi ý trong Start.","Apps and files recently opened that Windows Search records for Start suggestions."},
   {"Thống kê dùng thanh tác vụ (FeatureUsage)","Taskbar usage statistics (FeatureUsage)"},{"Số lần chuyển ứng dụng, mở Jump List, bấm biểu tượng khay; Windows dùng để đo mức dùng.","Counts of app switches, Jump List opens and tray clicks that Windows keeps for usage metrics."},
   {"Vị trí / kích thước cửa sổ thư mục (ShellBags)","Folder window layout (ShellBags)"},{"Explorer nhớ cách xem từng thư mục (cột, sắp xếp, kích cỡ cửa sổ) — cũng là danh sách mọi thư mục bạn đã mở, kể cả trên USB đã rút. Dọn sẽ đưa mọi thư mục về cách xem mặc định.","Explorer remembers how each folder is viewed (columns, sorting, window size) — which is also a list of every folder you opened, including on removed USB drives. Cleaning resets every folder to the default view."},
   {"Microsoft Office — tệp và vị trí gần đây","Microsoft Office — recent files and places"},{"File MRU / Place MRU của Word, Excel, PowerPoint… (mọi phiên bản, kể cả danh sách theo tài khoản) và shortcut trong thư mục Office\\Recent.","File MRU / Place MRU of Word, Excel, PowerPoint… (every version, including per-account lists) and the shortcuts in the Office\\Recent folder."},
   {"Microsoft Office — shortcut gần đây","Microsoft Office — recent shortcuts"},{"Shortcut .lnk trong %APPDATA%\\Microsoft\\Office\\Recent mà Office dùng cho danh sách Recent.",".lnk shortcuts in %APPDATA%\\Microsoft\\Office\\Recent that Office uses for its Recent list."},
   {"Adobe Acrobat / Reader — tệp gần đây","Adobe Acrobat / Reader — recent files"},{"cRecentFiles / cRecentFolders của Acrobat và Acrobat Reader.","cRecentFiles / cRecentFolders of Acrobat and Acrobat Reader."},
   {"Chrome / Edge / Brave — phiên và tab đã đóng gần đây","Chrome / Edge / Brave — sessions and recently closed tabs"},{"Sessions (Current/Last Session, Tabs): danh sách tab đang mở và «mở lại tab đã đóng». Trình duyệt sẽ khởi động với trang mới. Mặc định không chọn.","Sessions (Current/Last Session, Tabs): the open-tab list and \"reopen closed tab\". The browser starts with a fresh page. Unchecked by default."},
   {"Xóa cookie đăng nhập của mọi trang web trừ danh sách «Cookie giữ lại»; bạn sẽ phải đăng nhập lại các trang khác. Mặc định không chọn.","Removes login cookies of every website except the \"Keep cookies\" list; you will have to sign in again elsewhere. Unchecked by default."},
   {"Firefox — lịch sử duyệt web (giữ dấu trang)","Firefox — browsing history (bookmarks kept)"},{"Xóa lượt truy cập và địa chỉ đã gõ trong places.sqlite bằng SQL; dấu trang, mật khẩu, cookie giữ nguyên. Cần winsqlite3.dll (Windows 10+).","Deletes visits and typed URLs from places.sqlite with SQL; bookmarks, passwords and cookies stay. Needs winsqlite3.dll (Windows 10+)."},
   {"Firefox — cookie (đăng xuất mọi web)","Firefox — cookies (signs you out everywhere)"},{"cookies.sqlite của từng hồ sơ trừ danh sách «Cookie giữ lại». Mặc định không chọn.","cookies.sqlite of every profile except the \"Keep cookies\" list. Unchecked by default."},
   {"Cookie giữ lại…","Keep cookies…"},{"Cookie giữ lại","Keep cookies"},{"Lưu","Save"},{"Dọn khi thoát Tweek Pro","Clean when Tweek Pro exits"},{"  •  xóa theo dòng (SQL)","  •  row-level (SQL)"},
   {"Dấu vết: các loại đang đánh dấu sẽ được dọn (vào Kho) mỗi khi đóng Tweek Pro; trình duyệt đang chạy sẽ được bỏ qua.","Tracks: the checked types will be cleaned (to the vault) every time Tweek Pro closes; running browsers are skipped."},
   {"Dấu vết: giữ cookie của {0} trang: {1}","Tracks: keeping cookies of {0} sites: {1}"},
   {"Mỗi dòng một tên miền (ví dụ google.com giữ cả mail.google.com). Khi dọn cookie, chỉ các trang này còn đăng nhập; cookie khác bị xóa theo dòng bằng SQL và bản sao đầy đủ nằm trong Kho.","One domain per line (e.g. google.com also keeps mail.google.com). When cookies are cleaned only these sites stay signed in; other cookies are deleted row by row with SQL and a full copy goes to the vault."},
   {"Danh sách áp dụng cho Chrome / Edge / Brave và Firefox. Để trống = xóa toàn bộ cookie (chuyển cả tệp vào Kho).","The list applies to Chrome / Edge / Brave and Firefox. Empty = remove all cookies (the whole file moves to the vault)."},
   {"Máy này không có winsqlite3.dll (Windows 10+), nên danh sách chưa dùng được: cookie sẽ bị dọn toàn bộ.","This PC has no winsqlite3.dll (Windows 10+), so the list cannot be applied: cookies are removed entirely."},
   {"Dấu vết là dữ liệu Windows và trình duyệt ghi lại thói quen dùng máy: tệp mở gần đây, Jump List, lịch sử Run, hộp Mở/Lưu, từ khóa tìm, Office/Acrobat gần đây, Remote Desktop, PowerShell, lịch sử duyệt web. Chỉ những khóa HKCU và thư mục trong danh sách cho phép mới được dọn; không đụng mật khẩu, dấu trang, tiện ích. Mọi thứ đi vào Kho khôi phục. Cookie mặc định không chọn; «Cookie giữ lại» giữ đăng nhập của các trang bạn nêu tên. «Dọn khi thoát» dọn lại các loại đang đánh dấu mỗi lần đóng Tweek Pro.","Tracks are the data Windows and browsers keep about how you use the PC: recent files, Jump Lists, Run history, Open/Save dialogs, search terms, recent Office/Acrobat files, Remote Desktop, PowerShell, browsing history. Only the allow-listed HKCU keys and folders are cleaned; passwords, bookmarks and extensions are untouched. Everything goes to the Recovery Vault. Cookies start unchecked; \"Keep cookies\" preserves the sign-ins of the sites you name. \"Clean on exit\" re-cleans the checked types every time Tweek Pro closes."},
   {"Chrome / Edge / Brave — lịch sử duyệt web","Chrome / Edge / Brave — browsing history"},{"History, Visited Links, Top Sites, Shortcuts của từng hồ sơ. Không đụng mật khẩu, dấu trang, tiện ích. Khóa khi trình duyệt còn chạy.","History, Visited Links, Top Sites, Shortcuts of every profile. Passwords, bookmarks and extensions are untouched. Locked while the browser runs."},
   {"Chrome / Edge / Brave — cookie (đăng xuất mọi web)","Chrome / Edge / Brave — cookies (signs you out everywhere)"},
   {"Firefox — lịch sử biểu mẫu và phiên","Firefox — form history and sessions"},{"formhistory.sqlite (chuỗi đã gõ vào ô nhập) và sessionstore-backups. Không đụng places.sqlite (lịch sử + dấu trang), mật khẩu, cookie.","formhistory.sqlite (strings typed into fields) and sessionstore-backups. places.sqlite (history + bookmarks), passwords and cookies are untouched."},
   {"Chưa xem trước.\r\nBấm Xem trước để đếm tệp và giá trị Registry của từng loại dấu vết. Chưa có gì bị thay đổi cho đến khi bạn bấm Dọn và xác nhận.","Not previewed yet.\r\nClick Preview to count the files and registry values of each track type. Nothing changes until you click Clean and confirm."},
   {"  •  nhạy cảm","  •  sensitive"},
   {"{0} loại dấu vết  •  Đã chọn {1} loại, {2} mục, {3}  •  Chuyển vào Kho: khôi phục được, không ghi đè mục mới hơn","{0} track types  •  Selected {1} types, {2} items, {3}  •  To vault: restorable, never overwrites newer entries"},
   {"Dấu vết: đang xem trước {0} loại (chỉ đọc).","Tracks: previewing {0} types (read-only)."},{"Xem trước xong: {0} mục, {1} tệp","Preview finished: {0} items, {1} of files"},
   {"  •  {0} loại bị khóa (đóng trình duyệt rồi xem trước lại)","  •  {0} types locked (close the browser and preview again)"},{"Dấu vết: {0} mục, {1}, {2} loại bị khóa.","Tracks: {0} items, {1}, {2} types locked."},
   {"Không tìm thấy dấu vết nào trong các vị trí cho phép.","No tracks found in the allowed locations."},
   {"Xem trước rồi đánh dấu loại dấu vết muốn dọn.","Preview first, then check the track types to clean."},
   {"Bạn đã chọn cookie đăng nhập: mọi trang web sẽ yêu cầu đăng nhập lại. Tiếp tục?","You selected login cookies: every website will ask you to sign in again. Continue?"},
   {"Dọn {0} mục dấu vết vào Kho khôi phục?\r\n\r\n{1}\r\n\r\nMỗi loại tạo một bản sao lưu; giá trị Registry được ghi lại khi khôi phục nếu chưa có mục mới hơn.","Clean {0} track items into the Recovery Vault?\r\n\r\n{1}\r\n\r\nEach type creates one backup; registry values are written back on restore unless newer entries exist."},
   {"{0} mục","{0} items"},{" mục"," items"},
   {"Đã dọn {0} mục ({1}). Bỏ qua vì đang dùng: {2}. Lỗi: {3}. Bản sao lưu: {4}.","Cleaned {0} items ({1}). Skipped in use: {2}. Errors: {3}. Backups: {4}."},
   {"Dấu vết: ","Tracks: "},{"Dọn dấu vết lỗi: ","Track cleanup error: "},{"Kết quả dọn dấu vết","Track cleanup result"},
   {"Chọn một loại dấu vết để xem mục.","Select a track type to view its items."},{"Mục sẽ dọn — ","Items to clean — "},{"Đường dẫn / giá trị","Path / value"},
   {"Đang chạy: chrome — đóng trình duyệt rồi xem trước lại.","Running: chrome — close the browser and preview again."}
  };
 }
}
