using System;
using System.Collections.Generic;

namespace TweekPro.SysSpace {
 /// <summary>English strings for the System Space tab; merged by Core.L (keys must not repeat in other tables).</summary>
 public static class SystemSpaceLang {
  public static readonly Dictionary<string,string> Table=new Dictionary<string,string>(StringComparer.Ordinal){
   {"Dung lượng hệ thống","System Space"},{"Công cụ Windows","Windows tool"},{"Nguồn điện","Power"},{"Sao lưu","Backups"},
   {"Đo dung lượng","Measure"},{"Chạy công cụ cho mục đang chọn","Run tool for selected item"},{"Mở Storage Sense","Open Storage Sense"},
   {"Windows.old — bản Windows trước","Windows.old — previous Windows"},{"Bản cài trước còn giữ để quay lui sau khi nâng cấp lớn; Windows tự xóa sau 10 ngày nhưng thường sót lại.","The previous installation kept for rollback after a feature upgrade; Windows removes it after 10 days but it often lingers."},
   {"Dọn bằng Disk Cleanup (Previous Installations)","Clean with Disk Cleanup (Previous Installations)"},{"Sau khi dọn sẽ KHÔNG thể quay lui về bản Windows trước.","After cleaning you can NO LONGER roll back to the previous Windows."},
   {"WinSxS — kho thành phần","WinSxS — component store"},{"Kho thành phần Windows chứa mọi phiên bản tệp hệ thống đã cập nhật. Chỉ dọn bằng DISM; không bao giờ xóa tay.","The Windows component store holding every updated system file version. Cleaned only through DISM; never deleted by hand."},
   {"DISM /StartComponentCleanup","DISM /StartComponentCleanup"},{"Chạy vài phút; không dùng /ResetBase nên vẫn gỡ được bản cập nhật gần nhất.","Takes a few minutes; /ResetBase is not used so the latest updates stay uninstallable."},
   {"Bộ đệm Delivery Optimization","Delivery Optimization cache"},{"Tệp cập nhật Windows/Store tải về để chia sẻ ngang hàng với máy khác trong mạng.","Windows/Store update files downloaded for peer sharing with other PCs on the network."},
   {"Delete-DeliveryOptimizationCache","Delete-DeliveryOptimizationCache"},{"Windows sẽ tải lại khi cần; không ảnh hưởng dữ liệu.","Windows re-downloads when needed; no data is affected."},
   {"Driver cũ trùng lặp trong DriverStore","Older duplicate drivers in the DriverStore"},{"Gói driver bên thứ ba còn nhiều phiên bản cho cùng một INF; chỉ đề xuất bản cũ hơn, bỏ qua driver hộp và driver khởi động.","Third-party driver packages with several versions of the same INF; only older versions are proposed, inbox and boot-critical drivers are skipped."},
   {"pnputil /delete-driver (không cưỡng bức)","pnputil /delete-driver (no force)"},{"pnputil từ chối gói đang được thiết bị dùng — đó là lớp an toàn, Tweek Pro không dùng /force.","pnputil refuses packages a device is using — that is the safety net; Tweek Pro never uses /force."},
   {"hiberfil.sys — tệp ngủ đông","hiberfil.sys — hibernation file"},{"Ảnh RAM cho Hibernate và Fast Startup, thường 40–75% dung lượng RAM.","RAM image for Hibernate and Fast Startup, usually 40–75% of RAM size."},
   {"powercfg /hibernate off","powercfg /hibernate off"},{"Tắt luôn Hibernate và Fast Startup; bật lại bằng powercfg /hibernate on.","Also disables Hibernate and Fast Startup; re-enable with powercfg /hibernate on."},
   {"pagefile.sys + swapfile.sys","pagefile.sys + swapfile.sys"},{"Bộ nhớ ảo do Windows quản lý. Chỉ hiển thị; đổi kích thước trong System Properties → Performance.","Virtual memory managed by Windows. Display only; resize in System Properties → Performance."},
   {"Mở System Properties → Performance","Open System Properties → Performance"},
   {"Điểm khôi phục hệ thống (Shadow Copies)","System restore points (Shadow Copies)"},{"Dung lượng System Restore / Volume Shadow Copy đang dùng trên các ổ. Chỉ hiển thị; xóa điểm cũ trong System Protection.","Space used by System Restore / Volume Shadow Copy on each drive. Display only; delete old points in System Protection."},
   {"Mở System Protection","Open System Protection"},
   {"Thùng rác (mọi ổ đĩa)","Recycle Bin (all drives)"},{"Tệp đã xóa còn nằm trong $Recycle.Bin của tất cả ổ cố định.","Deleted files still sitting in $Recycle.Bin on every fixed drive."},
   {"Clear-RecycleBin","Clear-RecycleBin"},{"Tệp trong thùng rác bị xóa hẳn, không qua Kho khôi phục.","Recycle Bin contents are deleted for good, bypassing the Recovery Vault."},
   {"Những vùng này thuộc Windows nên Tweek Pro không tự xóa tệp: mỗi mục có đúng một công cụ chính chủ (Disk Cleanup cho Windows.old, DISM cho WinSxS, pnputil cho driver cũ, powercfg cho hiberfil, cmdlet cho Delivery Optimization và Thùng rác). Riêng gói MSI/MSP mồ côi trong Windows\\Installer được chuyển vào Kho khôi phục. Cột «Ước tính thu hồi» cho biết công cụ sẽ giải phóng bao nhiêu (WinSxS lấy từ DISM /AnalyzeComponentStore). Công cụ chạy nền, có thể theo dõi tiến độ ở dòng trạng thái. Cần quyền quản trị.","These areas belong to Windows, so Tweek Pro never deletes their files itself: each item maps to exactly one first-party tool (Disk Cleanup for Windows.old, DISM for WinSxS, pnputil for old drivers, powercfg for hiberfil, cmdlets for Delivery Optimization and the Recycle Bin). Only orphaned MSI/MSP packages in Windows\\Installer are moved into the Recovery Vault. The \"Estimated reclaim\" column shows how much the tool will free (WinSxS comes from DISM /AnalyzeComponentStore). Tools run in the background with progress in the status line. Administrator rights required."},
   {"Chưa đo.\r\nBấm Đo dung lượng để xem Windows.old, WinSxS, Delivery Optimization, driver cũ, gói Installer mồ côi, hiberfil, pagefile, điểm khôi phục và thùng rác chiếm bao nhiêu và có thể thu hồi bao nhiêu. Chỉ đọc.","Not measured yet.\r\nClick Measure to see how much Windows.old, WinSxS, Delivery Optimization, old drivers, orphaned Installer packages, hiberfil, pagefile, restore points and the Recycle Bin occupy and how much can be reclaimed. Read-only."},
   {"Chưa đo.","Not measured."},{"Đang đo…","Measuring…"},{"Chỉ hiển thị","Display only"},{"Không có / không áp dụng","Absent / not applicable"},{"Có thể tắt (đảo ngược được)","Can be turned off (reversible)"},{"Có thể dọn bằng công cụ Windows","Cleanable with a Windows tool"},{"Có thể chuyển vào Kho (khôi phục được)","Can move to the vault (restorable)"},
   {"Ước tính thu hồi","Estimated reclaim"},{"Ước tính thu hồi: ","Estimated reclaim: "},{"Ước tính: ","Estimate: "},{"tùy chọn","your choice"},
   {"Đang chiếm {0}  •  Ước tính thu hồi được: khoảng {1}  •  Công cụ Windows không qua Kho; gói Installer mồ côi có qua Kho","Occupying {0}  •  Estimated reclaimable: about {1}  •  Windows tools bypass the vault; orphaned Installer packages go through it"},
   {"Windows\\Installer — gói MSI/MSP mồ côi","Windows\\Installer — orphaned MSI/MSP packages"},{"Bản cache .msi/.msp mà không sản phẩm hay bản vá nào còn tham chiếu (LocalPackage trong Installer\\UserData). Thường vài GB sau nhiều năm cập nhật Office, driver, runtime.","Cached .msi/.msp files no product or patch references any more (LocalPackage under Installer\\UserData). Often several GB after years of Office, driver and runtime updates."},
   {"Chuyển vào Kho khôi phục (Tweek Pro)","Move to the Recovery Vault (Tweek Pro)"},{"Chỉ những tệp không còn được tham chiếu và cũ hơn 1 ngày. Nếu sau đó một ứng dụng báo thiếu gói khi sửa/gỡ, khôi phục tệp từ Kho.","Only files nothing references any more and older than 1 day. If an application later reports a missing package while repairing/uninstalling, restore the file from the vault."},
   {"Toàn bộ tệp biến mất khi tắt Hibernate.","The whole file disappears when Hibernate is turned off."},{"Toàn bộ thùng rác.","The whole Recycle Bin."},{"Tùy số điểm khôi phục bạn xóa trong System Protection.","Depends on how many restore points you delete in System Protection."},
   {"Tổng các gói cũ; pnputil có thể từ chối gói đang dùng.","Sum of the older packages; pnputil may refuse packages in use."},{"Toàn bộ, khôi phục được từ Kho.","All of it, restorable from the vault."},{"Gần như toàn bộ thư mục.","Almost the whole folder."},{"Toàn bộ bộ đệm; Windows tải lại khi cần.","The whole cache; Windows re-downloads when needed."},
   {"Cần quyền quản trị để DISM ước tính.","Administrator rights needed for the DISM estimate."},{"DISM không trả về số liệu đọc được.","DISM returned no readable figures."},
   {"Không đọc được danh sách sản phẩm MSI — bỏ qua để tránh xóa nhầm.","Could not read the MSI product list — skipped to avoid deleting the wrong files."},{"Không đọc được danh sách sản phẩm MSI — dừng để tránh xóa nhầm.","Could not read the MSI product list — stopped to avoid deleting the wrong files."},
   {"Không có gói mồ côi nào để chuyển.","No orphaned packages to move."},{"Mục này đi qua Kho khôi phục; dùng MoveOrphans.","This item goes through the Recovery Vault; use MoveOrphans."},{"Không chuyển được gói nào.","No package could be moved."},
   {"Đọc Installer\\UserData…","Reading Installer\\UserData…"},{"Dism /AnalyzeComponentStore…","Dism /AnalyzeComponentStore…"},{"Get-WindowsDriver -Online…","Get-WindowsDriver -Online…"},
   {" tệp, "," files, "},{"Chuyển các tệp này vào Kho khôi phục?","Move these files into the Recovery Vault?"},{"Đang chuyển vào kho: ","Moving to the vault: "},
   {"Đã chuyển {0} vào Kho khôi phục (bản sao lưu {1}).","Moved {0} into the Recovery Vault (backup {1})."},{"Bỏ qua: ","Skipped: "},
   {"\r\n\r\nNếu một ứng dụng báo thiếu gói khi sửa/gỡ, khôi phục bản sao lưu này trong tab Kho khôi phục.","\r\n\r\nIf an application reports a missing package while repairing/uninstalling, restore this backup from the Recovery Vault tab."},
   {"Ổ đĩa trống thêm {0}.","Drive gained {0} of free space."},{"Gói Installer","Installer package"},
   {"41 gói mồ côi; 236 sản phẩm/bản vá còn tham chiếu 310 gói.","41 orphaned packages; 236 products/patches still reference 310 packages."},{"DISM: sao lưu và tính năng đã tắt 1,3 GB + bộ đệm 0 B.","DISM: backups and disabled features 1.3 GB + cache 0 B."},
   {"Dung lượng hệ thống: đang đo (chỉ đọc).","System Space: measuring (read-only)."},{"Đang đo: ","Measuring: "},{"Đo xong.","Measured."},{"Dung lượng hệ thống: ","System Space: "},{"Đã dừng đo.","Measurement stopped."},
   {"Chọn một mục để chạy công cụ.","Select an item to run its tool."},{"Mục này hiện không có gì để dọn hoặc chưa được đo.","This item has nothing to clean right now or has not been measured."},{"Không có lệnh nào để chạy cho mục này.","There is no command to run for this item."},
   {"Lệnh sẽ chạy:","Commands to run:"},{"Kết quả KHÔNG đi qua Kho khôi phục. Tiếp tục?","Results do NOT go through the Recovery Vault. Continue?"},{"Chạy công cụ Windows","Run Windows tool"},
   {"Đang chạy: ","Running: "},{"Dung lượng hệ thống: chạy {0} lệnh cho «{1}».","System Space: running {0} commands for \"{1}\"."},
   {"mã {0}, {1}s","code {0}, {1}s"},{"Đã chạy {0} lệnh: {1} thành công, {2} bị từ chối hoặc lỗi.","Ran {0} commands: {1} succeeded, {2} refused or failed."},{"Kết quả công cụ Windows","Windows tool result"},
   {"Chọn một mục để xem chi tiết.","Select an item to view details."},{"Vị trí: ","Location: "},{"Dung lượng: ","Size: "},{"Công cụ: ","Tool: "},
   {"Hibernate đang tắt.","Hibernate is off."},{"Không có Windows.old.","No Windows.old."},{"Thư mục không tồn tại.","Folder does not exist."},{"Không đủ quyền đọc.","Not enough permission to read."},{"3 bản cũ trong 112 gói.","3 older versions among 112 packages."}
  };
 }
}
