using System;
using System.Collections.Generic;

namespace TweekPro.Core {
 /// <summary>English translations keyed by the Vietnamese source string. Keep keys byte-identical to the literals in code and junk-rules.json.</summary>
 public static class LangEn {
  public static readonly Dictionary<string,string> Table=new Dictionary<string,string>(StringComparer.Ordinal){
   // Identity
   {"Trình quản lý Windows","Windows Manager"},
   {"Kiểm tra sức khỏe một nút  •  Gỡ ứng dụng và dọn phần còn sót  •  Dọn rác, tệp trùng, thư mục rỗng  •  Theo dõi mạng realtime  •  Mọi thao tác xóa đều sao lưu, hoàn tác được","One-click health check  •  Uninstall and clean leftovers  •  Junk, duplicates, empty folders  •  Realtime network view  •  Every deletion is backed up and reversible"},
   {"Sẵn sàng. Tweek Pro chỉ thay đổi dữ liệu khi bạn xác nhận.","Ready. Tweek Pro only changes data after you confirm."},
   {"Khởi động lại với quyền quản trị","Restart as administrator"},
   {"Quyền quản trị viên","Administrator"},{"Quyền người dùng","Standard user"},
   {"Tiếng Việt","Tiếng Việt"},{"English","English"},{"Chuyển sang tiếng Việt","Switch to Vietnamese"},{"Switch to English","Switch to English"},{"Xác nhận thao tác","Confirm action"},{"  •  cần quản trị","  •  administrator"},{" tệp  •  "," files  •  "},{"Băng thông: cần quyền quản trị","Bandwidth: administrator required"},{"ngày (0 = tất cả)","days (0 = all)"},{"Xóa bản sao lưu cũ hơn","Delete backups older than"},
   {"Đổi ngôn ngữ sang tiếng Anh và khởi động lại Tweek Pro?\r\n\r\nCài đặt và kho khôi phục được giữ nguyên.","Switch the language to English and restart Tweek Pro?\r\n\r\nSettings and the recovery vault are kept."},
   {"Đổi ngôn ngữ sang tiếng Việt và khởi động lại Tweek Pro?\r\n\r\nCài đặt và kho khôi phục được giữ nguyên.","Switch the language to Vietnamese and restart Tweek Pro?\r\n\r\nSettings and the recovery vault are kept."},

   // Tabs
   {"Tổng quan","Overview"},{"Ứng dụng","Applications"},{"Phần còn sót","Leftovers"},{"Dọn rác","Junk Cleaner"},{"Thư mục rỗng","Empty Folders"},
   {"Tệp trùng lặp","Duplicates"},{"Phân tích ổ đĩa","Disk Analyzer"},{"Kho khôi phục","Recovery Vault"},{"Khởi động","Startup"},{"Mạng","Network"},
   {"Công cụ","Tools"},{"Nhật ký","Log"},

   // Buttons
   {"Làm mới","Refresh"},{"Gỡ mục đã chọn","Uninstall selected"},{"Quét mục đang xem","Scan selected"},{"Xuất CSV","Export CSV"},{"Xuất báo cáo","Export report"},
   {"Quét lại lịch sử gỡ","Rescan uninstall history"},{"Quét siêu sâu","Deep scan"},{"Chọn tất cả","Select all"},{"Bỏ chọn tất cả","Deselect all"},{"Bỏ chọn","Deselect"},
   {"Xem mục","Inspect"},{"Xóa đã chọn (có sao lưu)","Delete selected (backed up)"},{"Làm mới kho","Refresh vault"},{"Khôi phục mục đang chọn","Restore selected"},
   {"Xóa vĩnh viễn mục đã đánh dấu","Permanently delete checked"},{"Dọn kho theo tuổi…","Purge by age…"},{"Mở kho","Open vault"},{"Mở thư mục nhật ký","Open log folder"},
   {"Mở thư mục dữ liệu","Open data folder"},{"Lưu cài đặt ngay","Save settings now"},{"Tải danh sách","Load list"},{"Tắt (sao lưu)","Disable (backed up)"},{"Bật lại từ kho","Re-enable from vault"},
   {"Mở công cụ","Open tool"},{"Nạp lại quy tắc","Reload rules"},{"Xem trước","Preview"},{"Dọn mục đã chọn","Clean selected"},{"Xem tệp","View files"},{"Dừng quét","Stop scan"},{"Dừng quét sâu","Stop deep scan"},
   {"Chọn thư mục…","Choose folder…"},{"Quét trùng lặp","Scan duplicates"},{"Dọn bản trùng đã chọn","Clean selected duplicates"},{"Mở thư mục gốc","Open root folder"},{"Sao chép vị trí","Copy location"},
   {"Quét thư mục rỗng","Scan empty folders"},{"Xóa thư mục đã chọn","Delete selected folders"},{"Mở vị trí","Open location"},{"Phân tích","Analyze"},
   {"Kiểm tra ngay","Check now"},{"Mở tab xử lý","Open fixing tab"},{"Sao chép báo cáo","Copy report"},{"Dừng kiểm tra","Stop check"},
   {"Tạm dừng","Pause"},{"Tiếp tục","Resume"},{"Bật băng thông (ETW)","Enable bandwidth (ETW)"},{"Dừng băng thông (ETW)","Stop bandwidth (ETW)"},
   {"Đóng","Close"},{"Hủy","Cancel"},{"Tiếp tục xóa vĩnh viễn…","Continue to permanent delete…"},{"Xóa đã chọn","Delete selected"},

   // Columns
   {"Phiên bản","Version"},{"Nhà phát hành","Publisher"},{"Dung lượng *","Size *"},{"Phạm vi","Scope"},{"Ngày cài / cập nhật","Installed / updated"},
   {"Loại","Kind"},{"Đường dẫn","Path"},{"Cơ sở đề xuất","Reason"},{"Ngày","Date"},{"Ứng dụng / nhóm","Application / group"},{"Trạng thái","State"},{"Dung lượng","Size"},
   {"Kho","Vault"},{"Đường dẫn gốc","Original path"},{"Tên khởi động","Startup name"},{"Lệnh / đích","Command / target"},{"Tình trạng","Status"},{"Công dụng","Purpose"},{"Mô tả","Description"},
   {"Quy tắc","Rule"},{"Tệp","Files"},{"Nhóm (bản giữ lại)","Group (kept copy)"},{"Số bản","Copies"},{"Dung lượng mỗi tệp","Size per file"},{"Tiết kiệm được","Reclaimable"},{"Thư mục bản giữ lại","Kept copy folder"},
   {"Thư mục rỗng (xóa sẽ dọn cả nhánh con rỗng)","Empty folder (deleting clears the whole empty branch)"},{"Số nhánh con","Sub-branches"},{"Mục","Item"},{"Vị trí","Location"},
   {"Khu vực","Area"},{"Đánh giá","Verdict"},{"Chi tiết","Details"},{"Có thể giải phóng","Reclaimable"},{"Mức","Level"},{"Xử lý ở tab","Fix in tab"},
   {"Tiến trình","Process"},{"PID","PID"},{"Hướng","Direction"},{"Giao thức","Protocol"},{"Cục bộ","Local"},{"Từ xa","Remote"},{"Máy từ xa","Remote host"},{"Đã gửi","Sent"},{"Đã nhận","Received"},{"Gửi/s","Sent/s"},{"Nhận/s","Recv/s"},
   {"Tài liệu truy vết","Trace documents"},{"Startup của Windows","Windows Startup"},

   // Labels
   {"Tìm kiếm","Search"},{"Chế độ dọn:","Clean mode:"},{"Chuyển vào Kho khôi phục (có thể hoàn tác)","Move to Recovery Vault (reversible)"},{"Xóa thẳng — KHÔNG thể khôi phục","Delete directly — CANNOT be undone"},
   {"Giữ lại bản:","Keep:"},{"Cũ nhất (bản gốc)","Oldest (original)"},{"Mới nhất","Newest"},{"Chu kỳ (giây)","Interval (s)"},{"Ẩn loopback","Hide loopback"},{"Phân giải tên máy","Resolve host names"},
   {"Quét sâu sau khi gỡ","Deep scan after uninstall"},

   // Notes and overlays
   {"Chưa kiểm tra.\r\nBấm Kiểm tra ngay để chấm điểm máy. Mỗi dòng kết quả chỉ ra tab có thể dọn an toàn.","Not checked yet.\r\nClick Check now to score this PC. Each result row points to the tab that can clean it safely."},
   {"Kiểm tra sức khỏe chỉ đọc: đo tệp rác theo quy tắc, mục còn sót chờ duyệt, thư mục rỗng trong Downloads, bản sao lưu cũ hơn tuổi dọn kho, số mục khởi động và dung lượng trống ổ hệ thống. Không xóa gì; bấm đúp một dòng để mở tab xử lý tương ứng.","The health check is read-only: it measures rule-matched junk, pending leftovers, empty folders in Downloads, vault backups older than the purge age, startup entries and free space on the system drive. Nothing is deleted; double-click a row to open the matching tab."},
   {"Đang đọc danh sách ứng dụng…\r\nTweek Pro đọc khóa Uninstall của HKLM/HKCU, không kích hoạt sửa chữa MSI.","Reading the application list…\r\nTweek Pro reads the HKLM/HKCU Uninstall keys and never triggers MSI repair."},
   {"Không tìm thấy ứng dụng desktop nào.\r\nTweek Pro đọc các khóa Uninstall của HKLM/HKCU; chưa gồm toàn bộ ứng dụng Microsoft Store.","No desktop applications found.\r\nTweek Pro reads the HKLM/HKCU Uninstall keys; Microsoft Store apps are not fully covered yet."},
   {"Chưa có mục còn sót.\r\nSau khi gỡ, cửa sổ quét sẽ chuyển các mục chưa xử lý vào đây. Có thể dùng Quét lại lịch sử gỡ hoặc Quét siêu sâu.","No leftovers yet.\r\nAfter an uninstall, the scan window moves unhandled items here. You can also use Rescan uninstall history or Deep scan."},
   {"Mục nghi còn sót, chưa chắc thuộc riêng ứng dụng và có thể chứa dữ liệu cá nhân. Chỉ dọn sau khi đăng ký cài đặt đã biến mất; mọi thao tác xóa đều được sao lưu vào kho.","Suspected leftovers may not belong solely to the application and may hold personal data. Clean only after the install registration is gone; every deletion is backed up to the vault."},
   {"Các mục dưới đây chỉ là nghi ngờ còn sót và có thể chứa dữ liệu cá nhân. Hãy kiểm tra đường dẫn trước khi chọn. Xóa sẽ chuyển mục vào Kho khôi phục, không xóa vĩnh viễn.","The items below are only suspected leftovers and may hold personal data. Check each path before selecting. Deleting moves items to the Recovery Vault, never permanently."},
   {"Chưa có bản sao lưu.\r\nCác mục xóa từ cửa sổ quét hoặc tab Phần còn sót sẽ xuất hiện ở đây để khôi phục.","No backups yet.\r\nItems deleted from the scan window or the Leftovers tab appear here for restoring."},
   {"Chưa có bản sao lưu.\r\nCác mục xóa từ cửa sổ quét, tab Phần còn sót hoặc Dọn rác sẽ xuất hiện ở đây để khôi phục hoặc xóa vĩnh viễn.","No backups yet.\r\nItems deleted from the scan window, Leftovers or Junk Cleaner appear here for restoring or permanent deletion."},
   {"Khôi phục đưa file, giá trị Registry hoặc tệp rác về vị trí gốc; không ghi đè đích đã tồn tại. Xóa vĩnh viễn mới giải phóng dung lượng và không thể hoàn tác. Kho cũ của AppCare (nếu còn) vẫn hiển thị và khôi phục được.","Restore puts files, Registry values or junk back where they came from and never overwrites an existing target. Only permanent deletion frees disk space and cannot be undone. A legacy AppCare vault (if present) is still listed and restorable."},
   {"Chưa xem trước.\r\nBấm Xem trước để liệt kê tệp rác theo từng quy tắc cùng dung lượng. Chưa có gì bị thay đổi cho đến khi bạn bấm Dọn mục đã chọn và xác nhận.","Not previewed yet.\r\nClick Preview to list junk files per rule with their size. Nothing changes until you click Clean selected and confirm."},
   {"Chỉ dọn tệp tạm, dump, báo cáo lỗi, bộ đệm và rác hệ thống theo quy tắc; không bao giờ chạm vào Documents, Desktop, Downloads, dữ liệu ứng dụng hay thư mục Windows cốt lõi (System32, WinSxS, Program Files bị chặn cứng trong mã). Nhóm “Rác hệ thống” cần quyền quản trị; nhóm cache trình duyệt bị khóa khi trình duyệt còn chạy.","Only rule-matched temp files, dumps, error reports, caches and system junk are cleaned; Documents, Desktop, Downloads, application data and core Windows folders are never touched (System32, WinSxS and Program Files are hard-blocked in code). The “System junk” group needs administrator rights; browser cache groups stay locked while the browser runs."},
   {"Chỉ xóa những gì bạn xác nhận; dung lượng được giải phóng ngay.","Only what you confirm is deleted; space is freed immediately."},
   {"Chưa quét.\r\nChọn một thư mục (ví dụ Downloads) rồi bấm Quét trùng lặp để tìm các tệp giống hệt nhau. Chưa có gì bị thay đổi cho đến khi bạn bấm Dọn bản trùng đã chọn và xác nhận.","Not scanned yet.\r\nChoose a folder (for example Downloads) and click Scan duplicates to find identical files. Nothing changes until you click Clean selected duplicates and confirm."},
   {"So khớp nội dung bằng SHA-256; chỉ các tệp giống hệt nhau mới được gom nhóm. Không quét thư mục hệ thống, Program Files hay dữ liệu Tweek Pro. Bản giữ lại không bao giờ bị xóa; các bản còn lại chuyển vào kho (mặc định) và có thể khôi phục.","Content is matched with SHA-256; only byte-identical files are grouped. System folders, Program Files and Tweek Pro data are never scanned. The kept copy is never deleted; the others move to the vault (default) and can be restored."},
   {"Bản “Giữ lại” không bị xóa. Danh sách chỉ để xem; chưa có gì bị thay đổi.","The “kept” copy is never deleted. This list is read-only; nothing has changed yet."},
   {"Chưa quét.\r\nChọn một thư mục rồi bấm Quét thư mục rỗng. Chưa có gì bị thay đổi cho đến khi bạn bấm Xóa thư mục đã chọn và xác nhận.","Not scanned yet.\r\nChoose a folder and click Scan empty folders. Nothing changes until you click Delete selected folders and confirm."},
   {"Chỉ liệt kê thư mục hoàn toàn rỗng (không chứa tệp nào ở mọi cấp con). Bỏ qua liên kết và không đụng thư mục hệ thống, Program Files hay dữ liệu Tweek Pro. Thư mục rỗng không chứa dữ liệu nên được xóa thẳng sau khi xác nhận; ứng dụng có thể tự tạo lại khi cần.","Only completely empty folders are listed (no files at any depth). Links are skipped and system folders, Program Files and Tweek Pro data are never touched. Empty folders hold no data, so they are deleted directly after confirmation; applications recreate them when needed."},
   {"Không tìm thấy thư mục rỗng nào trong thư mục này.","No empty folders found in this folder."},
   {"Chưa phân tích.\r\nChọn một thư mục rồi bấm Phân tích để xem dung lượng bị chiếm bởi thư mục con, phần mở rộng và tệp lớn nhất. Thao tác chỉ đọc, an toàn tuyệt đối.","Not analyzed yet.\r\nChoose a folder and click Analyze to see space used by subfolders, extensions and the largest files. Read-only and completely safe."},
   {"Chỉ đọc — không thay đổi gì trên đĩa. Hiển thị thư mục con chiếm nhiều dung lượng nhất, dung lượng theo phần mở rộng và các tệp lớn nhất để bạn tự quyết định. Bỏ qua liên kết (junction/symlink); giới hạn 1.000.000 tệp / 120 giây.","Read-only — nothing on disk changes. Shows the heaviest subfolders, usage by extension and the largest files so you decide. Links (junction/symlink) are skipped; limit 1,000,000 files / 120 seconds."},
   {"Thư mục này không có tệp nào đọc được.","This folder contains no readable files."},
   {"Không có dữ liệu để hiển thị.","Nothing to display."},
   {"Chưa tải mục khởi động.\r\nBấm Tải danh sách hoặc mở tab này để đọc Run/RunOnce và shortcut Startup.","Startup entries not loaded.\r\nClick Load list or open this tab to read Run/RunOnce and Startup shortcuts."},
   {"Không tìm thấy mục Run/RunOnce hoặc shortcut Startup.\r\nMục toàn máy có thể cần Run as administrator với cùng tài khoản Windows.","No Run/RunOnce entries or Startup shortcuts found.\r\nMachine-wide entries may require Run as administrator with the same Windows account."},
   {"Run, RunOnce và shortcut Startup của tài khoản hiện tại/toàn máy. Có đăng ký không có nghĩa Windows đang cho chạy. Bật lại áp dụng cho mục đã tắt bằng Tweek Pro.","Run, RunOnce and Startup shortcuts for the current user and the machine. Registered does not mean Windows currently runs it. Re-enable applies to entries disabled by Tweek Pro."},
   {"Chưa đọc bảng kết nối.\r\nMở tab này để bắt đầu làm mới tự động theo chu kỳ đã chọn, hoặc bấm Làm mới.","Connection table not read yet.\r\nOpen this tab to start auto-refresh at the chosen interval, or click Refresh."},
   {"Không có kết nối nào được Windows báo cáo.","Windows reports no connections."},
   {"Không có kết nối khớp với bộ lọc hiện tại.","No connections match the current filter."},
   {"Chỉ mở công cụ khi bạn chọn. Công cụ thiếu trên phiên bản Windows hiện tại sẽ được đánh dấu. SFC có thể sửa file hệ thống và yêu cầu quyền quản trị.","Tools open only when you choose them. Tools missing on this Windows edition are marked. SFC can repair system files and requires administrator rights."},

   // Health check engine
   {"Tệp rác","Junk files"},{"Khởi động cùng Windows","Startup with Windows"},{"Dung lượng trống","Free space"},
   {"Rất ít tệp rác","Very little junk"},{"Có một ít tệp rác","Some junk"},{"Nhiều tệp rác","A lot of junk"},{"Rất nhiều tệp rác","Excessive junk"},
   {"{0} tệp, {1}","{0} files, {1}"},{"; {0} nhóm đang bị khóa (trình duyệt còn chạy hoặc cần quyền quản trị)","; {0} groups locked (browser running or administrator required)"},
   {"Không có mục chờ duyệt","Nothing awaiting review"},{"Có mục còn sót chờ duyệt","Leftovers awaiting review"},{"Danh sách chờ duyệt trống.","The review list is empty."},{"{0} mục từ các lần gỡ trước chưa được xử lý.","{0} items from earlier uninstalls are still unhandled."},
   {"Không có thư mục rỗng","No empty folders"},{"Có thư mục rỗng","Empty folders present"},{"Không tìm thấy nhánh rỗng","No empty branches found"},{"{0} nhánh thư mục hoàn toàn rỗng","{0} completely empty folder branches"},{" trong {0}"," in {0}"},
   {"Kho trống","Vault is empty"},{"Kho gọn","Vault is tidy"},{"Kho giữ bản sao lưu cũ","Vault holds old backups"},{"Chưa có bản sao lưu.","No backups yet."},
   {"{0} bản sao lưu ({1}); {2} bản cũ hơn {3} ngày có thể xóa vĩnh viễn bằng Dọn kho theo tuổi… ({4}).","{0} backups ({1}); {2} older than {3} days can be purged with Purge by age… ({4})."},
   {"Ít mục khởi động","Few startup entries"},{"Khá nhiều mục khởi động","Quite a few startup entries"},{"Quá nhiều mục khởi động","Too many startup entries"},{"{0} mục đang bật (Run/RunOnce/Startup). Mỗi mục kéo dài thời gian mở máy.","{0} entries enabled (Run/RunOnce/Startup). Each one lengthens boot time."},
   {"Còn đủ chỗ trống","Enough free space"},{"Chỗ trống bắt đầu ít","Free space getting low"},{"Sắp đầy","Nearly full"},{"Gần như đầy","Almost full"},{"Ổ hệ thống","System drive"},{"Ổ {0}","Drive {0}"},
   {"{0} còn trống {1} / {2} ({3}%).","{0} has {1} free of {2} ({3}%)."},
   {"Chưa đo được","Not measured"},{"Không đọc được dữ liệu khu vực này trong lần kiểm tra vừa rồi.","This area could not be read during the last check."},{"Chưa đo","Not measured"},
   {"Rất tốt","Excellent"},{"Tốt","Good"},{"Nên dọn","Worth cleaning"},{"Cần dọn","Needs cleaning"},{"Cần xử lý ngay","Act now"},{"Khẩn","Urgent"},{"Nên xem","Review"},
   {"Máy đang sạch. Không có gì cần dọn ở các khu vực đã kiểm tra.","This PC is clean. Nothing to clean in the checked areas."},
   {" Có thể giải phóng khoảng {0}."," About {0} can be freed."},{"{0} khu vực cần chú ý.","{0} areas need attention."},{" Nên dọn ngay để máy nhẹ hơn."," Clean now to lighten the PC."},
   {"Chưa kiểm tra","Not checked yet"},{"Đang kiểm tra…","Checking…"},
   {"Bấm Kiểm tra ngay để đo tệp rác, phần còn sót, thư mục rỗng, kho khôi phục, mục khởi động và dung lượng trống. Chỉ đọc, không thay đổi gì.","Click Check now to measure junk, leftovers, empty folders, the vault, startup entries and free space. Read-only; nothing changes."},
   {"Có thể giải phóng: {0}   •   {1} khu vực cần chú ý   •   Kiểm tra lúc {2}","Reclaimable: {0}   •   {1} areas need attention   •   Checked at {2}"},
   {"Tweek Pro – Kiểm tra sức khỏe máy {0}","Tweek Pro – PC health check {0}"},{"Điểm: {0}/100 ({1} – {2}). {3}","Score: {0}/100 ({1} – {2}). {3}"},{"chưa đo","not measured"},
   {"Đang đo tệp rác theo quy tắc…","Measuring rule-matched junk…"},{"Đang đo kho khôi phục…","Measuring the recovery vault…"},{"Đang đếm mục khởi động…","Counting startup entries…"},{"Đang tìm thư mục rỗng trong Downloads…","Finding empty folders in Downloads…"},{"Đang đọc dung lượng trống…","Reading free space…"},
   {"Kiểm tra sức khỏe: {0}/100 ({1}). {2}","Health check: {0}/100 ({1}). {2}"},{"Đã dừng kiểm tra sức khỏe.","Health check stopped."},{"Đã sao chép báo cáo sức khỏe vào clipboard.","Health report copied to the clipboard."},
   {"Chọn một dòng kết quả trước.","Select a result row first."},{"Không tìm thấy tab {0}.","Tab {0} not found."},{"Chưa có báo cáo. Bấm Kiểm tra ngay trước.","No report yet. Click Check now first."},

   // Windows apps (Appx/MSIX)
   {"Ứng dụng Windows","Windows Apps"},{"App Windows","Windows app"},{"Gói","Package"},{"Nguồn","Origin"},{"Gỡ cho mọi tài khoản","Remove for all accounts"},{"Không cài lại cho tài khoản mới","Do not reinstall for new accounts"},{"Hiện thành phần được bảo vệ","Show protected components"},
   {"Mở trong Microsoft Store","Open in Microsoft Store"},{"Mở thư mục gói","Open package folder"},{"Gỡ được","Removable"},{"Cần cân nhắc","Use caution"},{"Được bảo vệ","Protected"},{"Được bảo vệ (chỉ xem)","Protected (view only)"},{"Khác","Other"},
   {"Ứng dụng cài sẵn của Windows và ứng dụng Microsoft Store (gói Appx/MSIX). Gỡ qua Remove-AppxPackage của Windows; các thành phần cốt lõi (Start, Search, Settings, Windows Security, thư viện nền…) bị khóa trong mã và không thể chọn. Mục “Cần cân nhắc” gỡ được nhưng hữu ích (Store, App Installer, Photos…). Khôi phục: đăng ký lại từ thư mục gói nếu còn, hoặc cài lại từ Microsoft Store.","Windows inbox apps and Microsoft Store apps (Appx/MSIX packages). Removal uses Windows' own Remove-AppxPackage; core components (Start, Search, Settings, Windows Security, frameworks…) are locked in code and cannot be selected. “Use caution” items are removable but useful (Store, App Installer, Photos…). Restore: re-register from the package folder when it still exists, or reinstall from Microsoft Store."},
   {"Chưa tải danh sách.\r\nBấm Tải danh sách để đọc các gói Appx/MSIX đã cài (Get-AppxPackage). Chỉ đọc; chưa có gì bị thay đổi.","List not loaded.\r\nClick Load list to read the installed Appx/MSIX packages (Get-AppxPackage). Read-only; nothing changes."},
   {"Đang đọc danh sách gói qua PowerShell…","Reading the package list through PowerShell…"},{"Không đọc được gói nào.","No packages could be read."},{"Mọi gói đều được bảo vệ; bật “Hiện thành phần được bảo vệ” để xem.","Every package is protected; enable “Show protected components” to view them."},
   {"Ứng dụng Windows: {0} gói, {1} gỡ được, {2} được bảo vệ.","Windows apps: {0} packages, {1} removable, {2} protected."},{"{0} gói  •  {1} gỡ được  •  {2} được bảo vệ  •  Đã chọn {3}","{0} packages  •  {1} removable  •  {2} protected  •  Selected {3}"},{"  •  có mục cần cân nhắc","  •  includes caution items"},
   {"Đánh dấu ứng dụng muốn gỡ (thành phần được bảo vệ không thể chọn).","Check the apps to remove (protected components cannot be selected)."},{" cho mọi tài khoản"," for all accounts"},
   {"Gỡ {0} ứng dụng Windows{1}?\r\n\r\n{2}\r\n\r\nGỡ bằng Remove-AppxPackage. Khôi phục: đăng ký lại từ thư mục gói nếu Windows còn giữ, hoặc cài lại từ Microsoft Store.","Remove {0} Windows apps{1}?\r\n\r\n{2}\r\n\r\nRemoval uses Remove-AppxPackage. Restore: re-register from the package folder if Windows still keeps it, or reinstall from Microsoft Store."},
   {"\r\n\r\nBỏ provisioning: tài khoản Windows tạo mới cũng sẽ không có ứng dụng này.","\r\n\r\nDeprovision: newly created Windows accounts will not get this app either."},
   {"{0} mục thuộc nhóm “Cần cân nhắc”:\r\n{1}\r\n\r\nĐây là thành phần hữu ích của Windows (ví dụ Microsoft Store dùng để cài lại app khác). Vẫn gỡ?","{0} items are in the “Use caution” group:\r\n{1}\r\n\r\nThese are useful Windows components (for example Microsoft Store is needed to reinstall other apps). Remove anyway?"},
   {"Đang gỡ ứng dụng Windows: ","Removing Windows app: "},{"Đã gỡ: ","Removed: "},{"Không gỡ được ","Could not remove "},{"Ứng dụng chưa gỡ","App not removed"},{"Đã gỡ {0} ứng dụng Windows; lỗi {1}.","Removed {0} Windows apps; {1} errors."},{"Kết quả gỡ ứng dụng Windows","Windows app removal result"},
   {"Chọn một ứng dụng trước.","Select an app first."},{"Thư mục gói không tồn tại hoặc không đọc được.","The package folder does not exist or cannot be read."},
   {"Gỡ được; cài lại từ Microsoft Store khi cần.","Removable; reinstall from Microsoft Store when needed."},{"Gỡ được nhưng nên cân nhắc: thành phần hữu ích của Windows hoặc cần để cài app khác.","Removable, but think twice: a useful Windows component or needed to install other apps."},
   {"Thư viện nền (framework) mà app khác phụ thuộc; Windows tự dọn khi không còn ai dùng.","Framework package other apps depend on; Windows removes it when nothing uses it."},{"Windows đánh dấu không thể gỡ.","Marked non-removable by Windows."},{"Thành phần cốt lõi của Windows (Start, Search, Settings, đăng nhập…); gỡ sẽ làm hỏng hệ thống.","Core Windows component (Start, Search, Settings, sign-in…); removing it breaks the system."},
   {"Không đọc được danh sách ứng dụng Windows: ","Could not read the Windows app list: "},{"Thành phần được bảo vệ, không gỡ: ","Protected component, not removed: "},{"Tên gói không hợp lệ: ","Invalid package name: "},
   {"Đã gỡ gói; khôi phục = đăng ký lại từ thư mục gói nếu còn, hoặc cài lại từ Microsoft Store.","Package removed; restore = re-register from the package folder if present, or reinstall from Microsoft Store."},{"Đăng ký lại gói thất bại: ","Re-registering the package failed: "},{"Thư mục gói không còn; đã mở trang Microsoft Store của {0} để cài lại.","The package folder is gone; opened the Microsoft Store page of {0} to reinstall."},{"Không phải bản sao lưu ứng dụng Windows.","Not a Windows app backup."},
   {"Không tìm thấy Windows PowerShell; tính năng này chỉ chạy trên Windows.","Windows PowerShell not found; this feature runs on Windows only."},{"PowerShell không phản hồi trong thời gian cho phép.","PowerShell did not respond within the allowed time."},

   // Vault states and stubborn files
   {"Đã sao lưu","Backed up"},{"Đã khôi phục","Restored"},{"Cần kiểm tra","Needs review"},{"Hẹn xóa khi khởi động lại","Delete at next reboot"},
   {"bỏ thuộc tính chỉ đọc/ẩn/hệ thống của {0} mục","cleared read-only/hidden/system on {0} entries"},{"chiếm quyền sở hữu và cấp toàn quyền cho Administrators","took ownership and granted Administrators full control"},
   {"{0} mục vẫn bị Windows chặn dù đã bỏ thuộc tính và chiếm quyền sở hữu (thường do một tiến trình đang giữ tệp):\r\n\r\n{1}\r\n\r\nHẹn xóa các mục này khi khởi động lại Windows? Chúng sẽ bị xóa thẳng lúc khởi động, KHÔNG có bản sao lưu để khôi phục.","Windows still blocks {0} items after clearing attributes and taking ownership (usually a process is holding the files):\r\n\r\n{1}\r\n\r\nSchedule them for deletion at the next Windows restart? They will be deleted directly at boot, with NO backup to restore."},
   {"Đã hẹn xóa khi khởi động lại: ","Scheduled for deletion at reboot: "},{"Vẫn bị chặn sau khi chiếm quyền sở hữu; có thể đang bị một tiến trình giữ. Đóng ứng dụng liên quan rồi thử lại.","Still blocked after taking ownership; a process may be holding it. Close the related application and try again."},

   // Junk cleaner runtime texts
   {"Bị khóa","Locked"},{"Chưa xem trước","Not previewed"},{"Không có gì để dọn","Nothing to clean"},{"Có thể dọn (chưa đủ)","Cleanable (partial)"},{"Có thể dọn","Cleanable"},
   {"{0} quy tắc  •  Đã chọn {1} nhóm, {2} tệp, {3}","{0} rules  •  Selected {1} groups, {2} files, {3}"},
   {"  •  XÓA THẲNG: không thể khôi phục","  •  DIRECT DELETE: cannot be undone"},{"  •  Chuyển vào Kho: chưa giải phóng dung lượng cho đến khi xóa vĩnh viễn trong kho","  •  Move to Vault: space is freed only after permanent deletion in the vault"},
   {"Xóa thẳng mục đã chọn","Delete selected directly"},{"Dọn mục đã chọn (vào kho)","Clean selected (to vault)"},
   {"Xem trước xong: {0} tệp, {1}","Preview done: {0} files, {1}"},{"  •  {0} nhóm bị khóa (di chuột lên dòng đỏ để xem lý do)","  •  {0} groups locked (hover a red row for the reason)"},
   {"Không có tệp rác đủ điều kiện theo quy tắc hiện tại.\r\nTệp mới hơn {0} giờ và tệp đang mở không được tính.","No junk matches the current rules.\r\nFiles newer than {0} hours and open files are not counted."},
   {"Đã dừng xem trước.","Preview stopped."},{"Xem trước rồi đánh dấu nhóm muốn dọn.","Preview first, then check the groups to clean."},
   {"XÓA THẲNG {0} tệp ({1}) mà KHÔNG lưu bản khôi phục?\r\n\r\n{2}\r\n\r\nThao tác này không thể hoàn tác. Chỉ tiếp tục khi chắc chắn các nhóm trên chỉ chứa bộ đệm/tệp tạm.","DELETE {0} files ({1}) DIRECTLY without a recovery copy?\r\n\r\n{2}\r\n\r\nThis cannot be undone. Continue only if you are sure the groups above hold nothing but caches/temporary files."},
   {"Xác nhận xóa vĩnh viễn","Confirm permanent deletion"},{"Xác nhận lần cuối: xóa thẳng {0} tệp, không có bản sao lưu?","Final confirmation: delete {0} files directly, with no backup?"},
   {"Chuyển {0} tệp ({1}) vào Kho khôi phục?\r\n\r\n{2}\r\n\r\nMỗi nhóm tạo một bản sao lưu; có thể khôi phục hoặc xóa vĩnh viễn sau trong tab Kho khôi phục. Dung lượng ổ đĩa chưa được giải phóng cho đến khi xóa vĩnh viễn.","Move {0} files ({1}) to the Recovery Vault?\r\n\r\n{2}\r\n\r\nEach group creates one backup; you can restore or permanently delete it later in the Recovery Vault tab. Disk space is freed only after permanent deletion."},
   {"Đang xóa thẳng…","Deleting directly…"},{"Đang chuyển vào kho…","Moving to vault…"},
   {"Đã xóa thẳng {0} tệp ({1}). Bỏ qua vì đang dùng: {2}. Lỗi: {3}.","Deleted {0} files directly ({1}). Skipped because in use: {2}. Errors: {3}."},
   {"Đã chuyển vào kho {0} tệp ({1}). Bỏ qua vì đang dùng: {2}. Lỗi: {3}.","Moved {0} files to the vault ({1}). Skipped because in use: {2}. Errors: {3}."},{" Bản sao lưu: {0}."," Backups: {0}."},
   {"\r\n\r\nLỗi đầu tiên:\r\n","\r\n\r\nFirst errors:\r\n"},{"\r\n\r\nCó thể khôi phục hoặc xóa vĩnh viễn trong tab Kho khôi phục.","\r\n\r\nYou can restore or permanently delete them in the Recovery Vault tab."},{"Kết quả dọn rác","Junk cleaning result"},
   {"Chọn một quy tắc để xem tệp.","Select a rule to view its files."},{"Tệp sẽ dọn — ","Files to clean — "},{"Sửa lần cuối","Last modified"},
   {"Hiển thị 2.000 tệp lớn nhất trong {0} tệp.","Showing the 2,000 largest of {0} files."},{"Chưa xem trước hoặc không có tệp đủ điều kiện.","Not previewed yet, or no file qualifies."},{"Danh sách chỉ để xem; chưa có gì bị thay đổi.","Read-only list; nothing has changed."},

   {"Không đọc được quy tắc dọn rác: ","Could not read junk rules: "},{"Đã nạp {0} quy tắc dọn rác từ {1}.","Loaded {0} junk rules from {1}."},{"Dọn rác: đang xem trước {0} quy tắc (chỉ đọc).","Junk: previewing {0} rules (read-only)."},
   {"Dọn rác: xem trước xong — {0} tệp, {1}, {2} nhóm bị khóa.","Junk: preview done — {0} files, {1}, {2} groups locked."},{"Dọn rác: bắt đầu xóa thẳng {0} tệp trong {1} nhóm.","Junk: deleting {0} files in {1} groups directly."},{"Dọn rác: bắt đầu chuyển vào kho {0} tệp trong {1} nhóm.","Junk: moving {0} files in {1} groups to the vault."},
   {"Dọn rác: ","Junk: "},{"Dọn rác lỗi: ","Junk error: "},
   // Junk rule groups and names (junk-rules.json)
   {"Hệ thống","System"},{"Trình duyệt","Browsers"},{"Bộ đệm","Caches"},{"Rác hệ thống (cần quyền quản trị)","System junk (administrator required)"},
   {"Tệp tạm của tài khoản (%TEMP%)","User temporary files (%TEMP%)"},{"Tệp tạm của Windows (C:\\Windows\\Temp)","Windows temporary files (C:\\Windows\\Temp)"},
   {"Tệp dump khi ứng dụng gặp lỗi (CrashDumps)","Application crash dumps (CrashDumps)"},{"Báo cáo lỗi Windows của tài khoản (WER)","User Windows Error Reporting (WER)"},
   {"Báo cáo lỗi Windows toàn máy (ProgramData\\WER)","Machine-wide Windows Error Reporting (ProgramData\\WER)"},{"Bộ đệm ảnh thu nhỏ của Explorer","Explorer thumbnail cache"},
   {"Google Chrome — bộ đệm","Google Chrome — cache"},{"Microsoft Edge — bộ đệm","Microsoft Edge — cache"},{"Brave — bộ đệm","Brave — cache"},{"Mozilla Firefox — bộ đệm","Mozilla Firefox — cache"},
   {"Bộ đệm web cũ của Windows (INetCache)","Legacy Windows web cache (INetCache)"},{"Bộ đệm shader của card đồ họa (DirectX / NVIDIA / AMD)","GPU shader cache (DirectX / NVIDIA / AMD)"},
   {"Gói Windows Update đã tải (SoftwareDistribution\\Download)","Downloaded Windows Update packages (SoftwareDistribution\\Download)"},{"Nhật ký bảo trì thành phần Windows (Logs\\CBS)","Component servicing logs (Logs\\CBS)"},
   {"Tệp dump lỗi hệ thống (Minidump, LiveKernelReports)","System crash dumps (Minidump, LiveKernelReports)"},{"Nhật ký cài đặt / nâng cấp Windows (Panther)","Windows setup / upgrade logs (Panther)"},
   {"Thành phần ActiveX/Java cũ (Downloaded Program Files)","Legacy ActiveX/Java components (Downloaded Program Files)"},
   // Junk rule descriptions
   {"Tệp tạm do ứng dụng để lại trong thư mục Temp của tài khoản hiện tại. Bỏ qua tệp mới hơn 24 giờ và tệp đang được mở.","Temporary files applications leave in the current user's Temp folder. Files newer than 24 hours and open files are skipped."},
   {"Thư mục Temp dùng chung của hệ thống. Cần quyền quản trị để đọc và dọn đầy đủ.","The shared system Temp folder. Administrator rights are needed to read and clean it fully."},
   {"Bản ghi bộ nhớ Windows tạo khi ứng dụng bị treo; chỉ hữu ích khi đang gỡ lỗi.","Memory dumps Windows writes when an application crashes; only useful while debugging."},
   {"Hàng đợi và kho báo cáo lỗi Windows Error Reporting trong hồ sơ người dùng.","Windows Error Reporting queue and archive in the user profile."},
   {"Hàng đợi báo cáo lỗi toàn máy. Cần quyền quản trị.","Machine-wide error report queue. Administrator rights required."},
   {"thumbcache_*.db và iconcache_*.db. Windows tạo lại khi cần; tệp đang được Explorer giữ sẽ bị bỏ qua.","thumbcache_*.db and iconcache_*.db. Windows rebuilds them on demand; files held open by Explorer are skipped."},
   {"Cache, Code Cache và GPUCache của mọi hồ sơ Chrome. Không đụng đến lịch sử, cookie, mật khẩu. Chỉ dọn khi Chrome đã đóng.","Cache, Code Cache and GPUCache of every Chrome profile. History, cookies and passwords are untouched. Cleaned only while Chrome is closed."},
   {"Cache, Code Cache và GPUCache của mọi hồ sơ Edge. Chỉ dọn khi Edge đã đóng (kể cả tiến trình nền).","Cache, Code Cache and GPUCache of every Edge profile. Cleaned only while Edge is closed (including background processes)."},
   {"Cache, Code Cache và GPUCache của mọi hồ sơ Brave. Chỉ dọn khi Brave đã đóng.","Cache, Code Cache and GPUCache of every Brave profile. Cleaned only while Brave is closed."},
   {"Thư mục cache2 của mọi hồ sơ Firefox. Không đụng đến lịch sử, cookie, mật khẩu. Chỉ dọn khi Firefox đã đóng.","The cache2 folder of every Firefox profile. History, cookies and passwords are untouched. Cleaned only while Firefox is closed."},
   {"Cache của Internet Explorer / WebView / Office web content. Không chứa mật khẩu hay lịch sử.","Cache of Internet Explorer / WebView / Office web content. Holds no passwords or history."},
   {"Shader đã biên dịch; trình điều khiển tự tạo lại khi cần. Game có thể giật nhẹ ở lần chạy đầu sau khi dọn.","Compiled shaders; the driver rebuilds them on demand. Games may stutter briefly on the first run after cleaning."},
   {"Bộ cài cập nhật Windows đã tải về và đã áp dụng. Windows tự tải lại nếu cần. Chỉ dọn tệp cũ hơn 7 ngày để không cắt ngang cập nhật đang chạy.","Downloaded and already-applied Windows Update packages. Windows re-downloads them if needed. Only files older than 7 days are cleaned so a running update is never interrupted."},
   {"Nhật ký của Component Based Servicing, có thể phình tới nhiều GB. Chỉ dọn tệp cũ hơn 7 ngày; nhật ký hiện tại được giữ.","Component Based Servicing logs, which can grow to several GB. Only files older than 7 days are cleaned; the current log is kept."},
   {"Bản ghi bộ nhớ Windows tạo khi màn hình xanh hoặc lỗi kernel; chỉ cần khi đang gỡ lỗi.","Memory dumps Windows writes after a blue screen or kernel error; only needed while debugging."},
   {"Nhật ký do trình cài đặt Windows để lại sau khi nâng cấp phiên bản. Chỉ dọn tệp cũ hơn 7 ngày.","Logs left by Windows Setup after a version upgrade. Only files older than 7 days are cleaned."},
   {"Thư mục kế thừa của Internet Explorer; hầu như luôn trống hoặc chỉ còn tàn dư.","Legacy Internet Explorer folder; almost always empty or holding remnants only."},
  };
 }
}
