using System;
using System.Collections.Generic;

namespace TweekPro.Core {
 /// <summary>English translations keyed by the Vietnamese source string. Keep keys byte-identical to the literals in code and junk-rules.json.</summary>
 public static class LangEn {
  public static readonly Dictionary<string,string> Table=new Dictionary<string,string>(StringComparer.Ordinal){
   // Identity
   {"Trình quản lý Windows","Windows Manager"},
   {"Kiểm tra sức khỏe một nút  •  Gỡ ứng dụng và dọn phần còn sót  •  Dọn rác, tệp trùng, thư mục rỗng  •  Theo dõi mạng realtime  •  Mọi thao tác xóa đều sao lưu, hoàn tác được","One-click health check  •  Uninstall and clean leftovers  •  Junk, duplicates, empty folders  •  Realtime network view  •  Every deletion is backed up and reversible"},
   {"Sẵn sàng. Tweek Pro chỉ thay đổi dữ liệu khi bạn xác nhận.","Ready. Tweek Pro only changes data after you confirm."},
   {"Khởi động lại với quyền quản trị","Restart as administrator"},
   {"Quyền quản trị viên","Administrator"},{"Quyền người dùng","Standard user"},
   {"Tiếng Việt","Tiếng Việt"},{"English","English"},{"Chuyển sang tiếng Việt","Switch to Vietnamese"},{"Switch to English","Switch to English"},{"Xác nhận thao tác","Confirm action"},{"  •  cần quản trị","  •  administrator"},{" tệp  •  "," files  •  "},{"Băng thông: cần quyền quản trị","Bandwidth: administrator required"},{"ngày (0 = tất cả)","days (0 = all)"},{"Xóa bản sao lưu cũ hơn","Delete backups older than"},
   {"Đổi ngôn ngữ sang tiếng Anh và khởi động lại Tweek Pro?\r\n\r\nCài đặt và kho khôi phục được giữ nguyên.","Switch the language to English and restart Tweek Pro?\r\n\r\nSettings and the recovery vault are kept."},
   {"Đổi ngôn ngữ sang tiếng Việt và khởi động lại Tweek Pro?\r\n\r\nCài đặt và kho khôi phục được giữ nguyên.","Switch the language to Vietnamese and restart Tweek Pro?\r\n\r\nSettings and the recovery vault are kept."},

   // Tabs
   {"Tổng quan","Overview"},{"Ứng dụng","Applications"},{"Phần còn sót","Leftovers"},{"Dọn rác","Junk Cleaner"},{"Thư mục rỗng","Empty Folders"},
   {"Tệp trùng lặp","Duplicates"},{"Phân tích ổ đĩa","Disk Analyzer"},{"Kho khôi phục","Recovery Vault"},{"Khởi động","Startup"},{"Mạng","Network"},
   {"Công cụ","Tools"},{"Nhật ký","Log"},

   // Buttons
   {"Làm mới","Refresh"},{"Gỡ mục đã chọn","Uninstall selected"},{"Quét mục đang xem","Scan selected"},{"Xuất CSV","Export CSV"},{"Xuất báo cáo","Export report"},
   {"Quét lại lịch sử gỡ","Rescan uninstall history"},{"Quét siêu sâu","Deep scan"},{"Chọn tất cả","Select all"},{"Bỏ chọn tất cả","Deselect all"},{"Bỏ chọn","Deselect"},
   {"Xem mục","Inspect"},{"Xóa đã chọn (có sao lưu)","Delete selected (backed up)"},{"Làm mới kho","Refresh vault"},{"Khôi phục mục đang chọn","Restore selected"},
   {"Xóa vĩnh viễn mục đã đánh dấu","Permanently delete checked"},{"Dọn kho theo tuổi…","Purge by age…"},{"Mở kho","Open vault"},{"Mở thư mục nhật ký","Open log folder"},
   {"Mở thư mục dữ liệu","Open data folder"},{"Lưu cài đặt ngay","Save settings now"},{"Tải danh sách","Load list"},{"Tắt (sao lưu)","Disable (backed up)"},{"Bật lại từ kho","Re-enable from vault"},
   {"Mở công cụ","Open tool"},{"Nạp lại quy tắc","Reload rules"},{"Xem trước","Preview"},{"Dọn mục đã chọn","Clean selected"},{"Xem tệp","View files"},{"Dừng quét","Stop scan"},{"Dừng quét sâu","Stop deep scan"},
   {"Chọn thư mục…","Choose folder…"},{"Quét trùng lặp","Scan duplicates"},{"Dọn bản trùng đã chọn","Clean selected duplicates"},{"Mở thư mục gốc","Open root folder"},{"Sao chép vị trí","Copy location"},
   {"Quét thư mục rỗng","Scan empty folders"},{"Xóa thư mục đã chọn","Delete selected folders"},{"Mở vị trí","Open location"},{"Phân tích","Analyze"},
   {"Kiểm tra ngay","Check now"},{"Mở tab xử lý","Open fixing tab"},{"Sao chép báo cáo","Copy report"},{"Dừng kiểm tra","Stop check"},
   {"Tạm dừng","Pause"},{"Tiếp tục","Resume"},{"Bật băng thông (ETW)","Enable bandwidth (ETW)"},{"Dừng băng thông (ETW)","Stop bandwidth (ETW)"},
   {"Đóng","Close"},{"Hủy","Cancel"},{"Tiếp tục xóa vĩnh viễn…","Continue to permanent delete…"},{"Xóa đã chọn","Delete selected"},

   // Columns
   {"Phiên bản","Version"},{"Nhà phát hành","Publisher"},{"Dung lượng *","Size *"},{"Phạm vi","Scope"},{"Ngày cài / cập nhật","Installed / updated"},
   {"Loại","Kind"},{"Đường dẫn","Path"},{"Cơ sở đề xuất","Reason"},{"Ngày","Date"},{"Ứng dụng / nhóm","Application / group"},{"Trạng thái","State"},{"Dung lượng","Size"},
   {"Kho","Vault"},{"Đường dẫn gốc","Original path"},{"Tên khởi động","Startup name"},{"Lệnh / đích","Command / target"},{"Tình trạng","Status"},{"Công dụng","Purpose"},{"Mô tả","Description"},
   {"Quy tắc","Rule"},{"Số tệp","Files"},{"Tệp","File"},{"Nhóm (bản giữ lại)","Group (kept copy)"},{"Số bản","Copies"},{"Dung lượng mỗi tệp","Size per file"},{"Tiết kiệm được","Reclaimable"},{"Thư mục bản giữ lại","Kept copy folder"},
   {"Thư mục rỗng (xóa sẽ dọn cả nhánh con rỗng)","Empty folder (deleting clears the whole empty branch)"},{"Số nhánh con","Sub-branches"},{"Mục","Item"},{"Vị trí","Location"},
   {"Khu vực","Area"},{"Đánh giá","Verdict"},{"Chi tiết","Details"},{"Có thể giải phóng","Reclaimable"},{"Mức","Level"},{"Xử lý ở tab","Fix in tab"},
   {"Tiến trình","Process"},{"PID","PID"},{"Hướng","Direction"},{"Giao thức","Protocol"},{"Cục bộ","Local"},{"Từ xa","Remote"},{"Máy từ xa","Remote host"},{"Đã gửi","Sent"},{"Đã nhận","Received"},{"Gửi/s","Sent/s"},{"Nhận/s","Recv/s"},
   {"Tài liệu truy vết","Trace documents"},{"Startup của Windows","Windows Startup"},

   // Labels
   {"Tìm kiếm","Search"},{"Chế độ dọn:","Clean mode:"},{"Chuyển vào Kho khôi phục (có thể hoàn tác)","Move to Recovery Vault (reversible)"},{"Xóa thẳng — KHÔNG thể khôi phục","Delete directly — CANNOT be undone"},
   {"Giữ lại bản:","Keep:"},{"Cũ nhất (bản gốc)","Oldest (original)"},{"Mới nhất","Newest"},{"Chu kỳ (giây)","Interval (s)"},{"Ẩn loopback","Hide loopback"},{"Phân giải tên máy","Resolve host names"},
   {"Quét sâu sau khi gỡ","Deep scan after uninstall"},

   // Notes and overlays
   {"Chưa kiểm tra.\r\nBấm Kiểm tra ngay để chấm điểm máy. Mỗi dòng kết quả chỉ ra tab có thể dọn an toàn.","Not checked yet.\r\nClick Check now to score this PC. Each result row points to the tab that can clean it safely."},
   {"Kiểm tra sức khỏe chỉ đọc: đo tệp rác theo quy tắc, mục còn sót chờ duyệt, thư mục rỗng trong Downloads, bản sao lưu cũ hơn tuổi dọn kho, số mục khởi động và dung lượng trống ổ hệ thống. Không xóa gì; bấm đúp một dòng để mở tab xử lý tương ứng.","The health check is read-only: it measures rule-matched junk, pending leftovers, empty folders in Downloads, vault backups older than the purge age, startup entries and free space on the system drive. Nothing is deleted; double-click a row to open the matching tab."},
   {"Đang đọc danh sách ứng dụng…\r\nTweek Pro đọc khóa Uninstall của HKLM/HKCU, không kích hoạt sửa chữa MSI.","Reading the application list…\r\nTweek Pro reads the HKLM/HKCU Uninstall keys and never triggers MSI repair."},
   {"Không tìm thấy ứng dụng desktop nào.\r\nTweek Pro đọc các khóa Uninstall của HKLM/HKCU; chưa gồm toàn bộ ứng dụng Microsoft Store.","No desktop applications found.\r\nTweek Pro reads the HKLM/HKCU Uninstall keys; Microsoft Store apps are not fully covered yet."},
   {"Chưa có mục còn sót.\r\nSau khi gỡ, cửa sổ quét sẽ chuyển các mục chưa xử lý vào đây. Có thể dùng Quét lại lịch sử gỡ hoặc Quét siêu sâu.","No leftovers yet.\r\nAfter an uninstall, the scan window moves unhandled items here. You can also use Rescan uninstall history or Deep scan."},
   {"Mục nghi còn sót, chưa chắc thuộc riêng ứng dụng và có thể chứa dữ liệu cá nhân. Chỉ dọn sau khi đăng ký cài đặt đã biến mất; mọi thao tác xóa đều được sao lưu vào kho.","Suspected leftovers may not belong solely to the application and may hold personal data. Clean only after the install registration is gone; every deletion is backed up to the vault."},
   {"Các mục dưới đây chỉ là nghi ngờ còn sót và có thể chứa dữ liệu cá nhân. Hãy kiểm tra đường dẫn trước khi chọn. Xóa sẽ chuyển mục vào Kho khôi phục, không xóa vĩnh viễn.","The items below are only suspected leftovers and may hold personal data. Check each path before selecting. Deleting moves items to the Recovery Vault, never permanently."},
   {"Chưa có bản sao lưu.\r\nCác mục xóa từ cửa sổ quét hoặc tab Phần còn sót sẽ xuất hiện ở đây để khôi phục.","No backups yet.\r\nItems deleted from the scan window or the Leftovers tab appear here for restoring."},
   {"Chưa có bản sao lưu.\r\nCác mục xóa từ cửa sổ quét, tab Phần còn sót hoặc Dọn rác sẽ xuất hiện ở đây để khôi phục hoặc xóa vĩnh viễn.","No backups yet.\r\nItems deleted from the scan window, Leftovers or Junk Cleaner appear here for restoring or permanent deletion."},
   {"Khôi phục đưa file, giá trị Registry hoặc tệp rác về vị trí gốc; không ghi đè đích đã tồn tại. Xóa vĩnh viễn mới giải phóng dung lượng và không thể hoàn tác. Kho cũ của AppCare (nếu còn) vẫn hiển thị và khôi phục được.","Restore puts files, Registry values or junk back where they came from and never overwrites an existing target. Only permanent deletion frees disk space and cannot be undone. A legacy AppCare vault (if present) is still listed and restorable."},
   {"Chưa xem trước.\r\nBấm Xem trước để liệt kê tệp rác theo từng quy tắc cùng dung lượng. Chưa có gì bị thay đổi cho đến khi bạn bấm Dọn mục đã chọn và xác nhận.","Not previewed yet.\r\nClick Preview to list junk files per rule with their size. Nothing changes until you click Clean selected and confirm."},
   {"Chỉ dọn tệp tạm, dump, báo cáo lỗi, bộ đệm và rác hệ thống theo quy tắc; không bao giờ chạm vào Documents, Desktop, Downloads, dữ liệu ứng dụng hay thư mục Windows cốt lõi (System32, WinSxS, Program Files bị chặn cứng trong mã). Nhóm “Rác hệ thống” cần quyền quản trị; nhóm cache trình duyệt bị khóa khi trình duyệt còn chạy.","Only rule-matched temp files, dumps, error reports, caches and system junk are cleaned; Documents, Desktop, Downloads, application data and core Windows folders are never touched (System32, WinSxS and Program Files are hard-blocked in code). The “System junk” group needs administrator rights; browser cache groups stay locked while the browser runs."},
   {"Chỉ xóa những gì bạn xác nhận; dung lượng được giải phóng ngay.","Only what you confirm is deleted; space is freed immediately."},
   {"Chưa quét.\r\nChọn một thư mục (ví dụ Downloads) rồi bấm Quét trùng lặp để tìm các tệp giống hệt nhau. Chưa có gì bị thay đổi cho đến khi bạn bấm Dọn bản trùng đã chọn và xác nhận.","Not scanned yet.\r\nChoose a folder (for example Downloads) and click Scan duplicates to find identical files. Nothing changes until you click Clean selected duplicates and confirm."},
   {"So khớp nội dung bằng SHA-256; chỉ các tệp giống hệt nhau mới được gom nhóm. Không quét thư mục hệ thống, Program Files hay dữ liệu Tweek Pro. Bản giữ lại không bao giờ bị xóa; các bản còn lại chuyển vào kho (mặc định) và có thể khôi phục.","Content is matched with SHA-256; only byte-identical files are grouped. System folders, Program Files and Tweek Pro data are never scanned. The kept copy is never deleted; the others move to the vault (default) and can be restored."},
   {"Bản “Giữ lại” không bị xóa. Danh sách chỉ để xem; chưa có gì bị thay đổi.","The “kept” copy is never deleted. This list is read-only; nothing has changed yet."},
   {"Chưa quét.\r\nChọn một thư mục rồi bấm Quét thư mục rỗng. Chưa có gì bị thay đổi cho đến khi bạn bấm Xóa thư mục đã chọn và xác nhận.","Not scanned yet.\r\nChoose a folder and click Scan empty folders. Nothing changes until you click Delete selected folders and confirm."},
   {"Chỉ liệt kê thư mục hoàn toàn rỗng (không chứa tệp nào ở mọi cấp con). Bỏ qua liên kết và không đụng thư mục hệ thống, Program Files hay dữ liệu Tweek Pro. Thư mục rỗng không chứa dữ liệu nên được xóa thẳng sau khi xác nhận; ứng dụng có thể tự tạo lại khi cần.","Only completely empty folders are listed (no files at any depth). Links are skipped and system folders, Program Files and Tweek Pro data are never touched. Empty folders hold no data, so they are deleted directly after confirmation; applications recreate them when needed."},
   {"Không tìm thấy thư mục rỗng nào trong thư mục này.","No empty folders found in this folder."},
   {"Chưa phân tích.\r\nChọn một thư mục rồi bấm Phân tích để xem dung lượng bị chiếm bởi thư mục con, phần mở rộng và tệp lớn nhất. Thao tác chỉ đọc, an toàn tuyệt đối.","Not analyzed yet.\r\nChoose a folder and click Analyze to see space used by subfolders, extensions and the largest files. Read-only and completely safe."},
   {"Chỉ đọc — không thay đổi gì trên đĩa. Hiển thị thư mục con chiếm nhiều dung lượng nhất, dung lượng theo phần mở rộng và các tệp lớn nhất để bạn tự quyết định. Bỏ qua liên kết (junction/symlink); giới hạn 1.000.000 tệp / 120 giây.","Read-only — nothing on disk changes. Shows the heaviest subfolders, usage by extension and the largest files so you decide. Links (junction/symlink) are skipped; limit 1,000,000 files / 120 seconds."},
   {"Thư mục này không có tệp nào đọc được.","This folder contains no readable files."},
   {"Không có dữ liệu để hiển thị.","Nothing to display."},
   {"Chưa tải mục khởi động.\r\nBấm Tải danh sách hoặc mở tab này để đọc Run/RunOnce và shortcut Startup.","Startup entries not loaded.\r\nClick Load list or open this tab to read Run/RunOnce and Startup shortcuts."},
   {"Không tìm thấy mục Run/RunOnce hoặc shortcut Startup.\r\nMục toàn máy có thể cần Run as administrator với cùng tài khoản Windows.","No Run/RunOnce entries or Startup shortcuts found.\r\nMachine-wide entries may require Run as administrator with the same Windows account."},
   {"Run, RunOnce và shortcut Startup của tài khoản hiện tại/toàn máy. Có đăng ký không có nghĩa Windows đang cho chạy. Bật lại áp dụng cho mục đã tắt bằng Tweek Pro.","Run, RunOnce and Startup shortcuts for the current user and the machine. Registered does not mean Windows currently runs it. Re-enable applies to entries disabled by Tweek Pro."},
   {"Chưa đọc bảng kết nối.\r\nMở tab này để bắt đầu làm mới tự động theo chu kỳ đã chọn, hoặc bấm Làm mới.","Connection table not read yet.\r\nOpen this tab to start auto-refresh at the chosen interval, or click Refresh."},
   {"Không có kết nối nào được Windows báo cáo.","Windows reports no connections."},
   {"Không có kết nối khớp với bộ lọc hiện tại.","No connections match the current filter."},
   {"Chỉ mở công cụ khi bạn chọn. Công cụ thiếu trên phiên bản Windows hiện tại sẽ được đánh dấu. SFC có thể sửa file hệ thống và yêu cầu quyền quản trị.","Tools open only when you choose them. Tools missing on this Windows edition are marked. SFC can repair system files and requires administrator rights."},
   {"Mỗi mục dùng icon hệ thống của tệp .exe/.cpl/.msc tương ứng. Chỉ mở công cụ khi bạn chọn. Công cụ thiếu trên phiên bản Windows hiện tại sẽ được đánh dấu. SFC/chkdsk có thể sửa hệ thống và yêu cầu quyền quản trị. Kiểm tra cập nhật hỏi GitHub Releases (tag v*), không theo từng push nhánh.","Each entry uses the system icon of its .exe/.cpl/.msc. Tools open only when you choose them. Tools missing on this Windows edition are marked. SFC/chkdsk can change the system and need administrator rights. Check for updates queries GitHub Releases (v* tags), not every branch push."},
   {"Dòng lệnh","Command-line"},

   // Health check engine
   {"Tệp rác","Junk files"},{"Khởi động cùng Windows","Startup with Windows"},{"Dung lượng trống","Free space"},
   {"Rất ít tệp rác","Very little junk"},{"Có một ít tệp rác","Some junk"},{"Nhiều tệp rác","A lot of junk"},{"Rất nhiều tệp rác","Excessive junk"},
   {"{0} tệp, {1}","{0} files, {1}"},{"; {0} nhóm đang bị khóa (trình duyệt còn chạy hoặc cần quyền quản trị)","; {0} groups locked (browser running or administrator required)"},
   {"Không có mục chờ duyệt","Nothing awaiting review"},{"Có mục còn sót chờ duyệt","Leftovers awaiting review"},{"Danh sách chờ duyệt trống.","The review list is empty."},{"{0} mục từ các lần gỡ trước chưa được xử lý.","{0} items from earlier uninstalls are still unhandled."},
   {"Không có thư mục rỗng","No empty folders"},{"Có thư mục rỗng","Empty folders present"},{"Không tìm thấy nhánh rỗng","No empty branches found"},{"{0} nhánh thư mục hoàn toàn rỗng","{0} completely empty folder branches"},{" trong {0}"," in {0}"},
   {"Kho trống","Vault is empty"},{"Kho gọn","Vault is tidy"},{"Kho giữ bản sao lưu cũ","Vault holds old backups"},{"Chưa có bản sao lưu.","No backups yet."},
   {"{0} bản sao lưu ({1}); {2} bản cũ hơn {3} ngày có thể xóa vĩnh viễn bằng Dọn kho theo tuổi… ({4}).","{0} backups ({1}); {2} older than {3} days can be purged with Purge by age… ({4})."},
   {"Ít mục khởi động","Few startup entries"},{"Khá nhiều mục khởi động","Quite a few startup entries"},{"Quá nhiều mục khởi động","Too many startup entries"},{"{0} mục đang bật (Run/RunOnce/Startup). Mỗi mục kéo dài thời gian mở máy.","{0} entries enabled (Run/RunOnce/Startup). Each one lengthens boot time."},
   {"Còn đủ chỗ trống","Enough free space"},{"Chỗ trống bắt đầu ít","Free space getting low"},{"Sắp đầy","Nearly full"},{"Gần như đầy","Almost full"},{"Ổ hệ thống","System drive"},{"Ổ {0}","Drive {0}"},
   {"{0} còn trống {1} / {2} ({3}%).","{0} has {1} free of {2} ({3}%)."},
   {"Chưa đo được","Not measured"},{"Không đọc được dữ liệu khu vực này trong lần kiểm tra vừa rồi.","This area could not be read during the last check."},{"Chưa đo","Not measured"},
   {"Rất tốt","Excellent"},{"Tốt","Good"},{"Nên dọn","Worth cleaning"},{"Cần dọn","Needs cleaning"},{"Cần xử lý ngay","Act now"},{"Khẩn","Urgent"},{"Nên xem","Review"},
   {"Máy đang sạch. Không có gì cần dọn ở các khu vực đã kiểm tra.","This PC is clean. Nothing to clean in the checked areas."},
   {" Có thể giải phóng khoảng {0}."," About {0} can be freed."},{"{0} khu vực cần chú ý.","{0} areas need attention."},{" Nên dọn ngay để máy nhẹ hơn."," Clean now to lighten the PC."},
   {"Chưa kiểm tra","Not checked yet"},{"Đang kiểm tra…","Checking…"},
   {"Bấm Kiểm tra ngay để đo tệp rác, phần còn sót, thư mục rỗng, kho khôi phục, mục khởi động và dung lượng trống. Chỉ đọc, không thay đổi gì.","Click Check now to measure junk, leftovers, empty folders, the vault, startup entries and free space. Read-only; nothing changes."},
   {"Có thể giải phóng: {0}   •   {1} khu vực cần chú ý   •   Kiểm tra lúc {2}","Reclaimable: {0}   •   {1} areas need attention   •   Checked at {2}"},
   {"Tweek Pro – Kiểm tra sức khỏe máy {0}","Tweek Pro – PC health check {0}"},{"Điểm: {0}/100 ({1} – {2}). {3}","Score: {0}/100 ({1} – {2}). {3}"},{"chưa đo","not measured"},
   {"Đang đo tệp rác theo quy tắc…","Measuring rule-matched junk…"},{"Đang đo kho khôi phục…","Measuring the recovery vault…"},{"Đang đếm mục khởi động…","Counting startup entries…"},{"Đang tìm thư mục rỗng trong Downloads…","Finding empty folders in Downloads…"},{"Đang đọc dung lượng trống…","Reading free space…"},
   {"Kiểm tra sức khỏe: {0}/100 ({1}). {2}","Health check: {0}/100 ({1}). {2}"},{"Đã dừng kiểm tra sức khỏe.","Health check stopped."},{"Đã sao chép báo cáo sức khỏe vào clipboard.","Health report copied to the clipboard."},
   {"Chọn một dòng kết quả trước.","Select a result row first."},{"Không tìm thấy tab {0}.","Tab {0} not found."},{"Chưa có báo cáo. Bấm Kiểm tra ngay trước.","No report yet. Click Check now first."},

   // Windows apps (Appx/MSIX)
   {"Ứng dụng Windows","Windows Apps"},{"App Windows","Windows app"},{"Gói","Package"},{"Nguồn","Origin"},{"Gỡ cho mọi tài khoản","Remove for all accounts"},{"Không cài lại cho tài khoản mới","Do not reinstall for new accounts"},{"Hiện thành phần được bảo vệ","Show protected components"},
   {"Mở trong Microsoft Store","Open in Microsoft Store"},{"Mở thư mục gói","Open package folder"},{"Gỡ được","Removable"},{"Cần cân nhắc","Use caution"},{"Được bảo vệ","Protected"},{"Được bảo vệ (chỉ xem)","Protected (view only)"},{"Khác","Other"},
   {"Ứng dụng cài sẵn của Windows và ứng dụng Microsoft Store (gói Appx/MSIX). Gỡ qua Remove-AppxPackage của Windows; các thành phần cốt lõi (Start, Search, Settings, Windows Security, thư viện nền…) bị khóa trong mã và không thể chọn. Mục “Cần cân nhắc” gỡ được nhưng hữu ích (Store, App Installer, Photos…). Khôi phục: đăng ký lại từ thư mục gói nếu còn, hoặc cài lại từ Microsoft Store.","Windows inbox apps and Microsoft Store apps (Appx/MSIX packages). Removal uses Windows' own Remove-AppxPackage; core components (Start, Search, Settings, Windows Security, frameworks…) are locked in code and cannot be selected. “Use caution” items are removable but useful (Store, App Installer, Photos…). Restore: re-register from the package folder when it still exists, or reinstall from Microsoft Store."},
   {"Chưa tải danh sách.\r\nBấm Tải danh sách để đọc các gói Appx/MSIX đã cài (Get-AppxPackage). Chỉ đọc; chưa có gì bị thay đổi.","List not loaded.\r\nClick Load list to read the installed Appx/MSIX packages (Get-AppxPackage). Read-only; nothing changes."},
   {"Đang đọc danh sách gói qua PowerShell…","Reading the package list through PowerShell…"},{"Không đọc được gói nào.","No packages could be read."},{"Mọi gói đều được bảo vệ; bật “Hiện thành phần được bảo vệ” để xem.","Every package is protected; enable “Show protected components” to view them."},
   {"Ứng dụng Windows: {0} gói, {1} gỡ được, {2} được bảo vệ.","Windows apps: {0} packages, {1} removable, {2} protected."},{"{0} gói  •  {1} gỡ được  •  {2} được bảo vệ  •  Đã chọn {3}","{0} packages  •  {1} removable  •  {2} protected  •  Selected {3}"},{"  •  có mục cần cân nhắc","  •  includes caution items"},
   {"Đánh dấu ứng dụng muốn gỡ (thành phần được bảo vệ không thể chọn).","Check the apps to remove (protected components cannot be selected)."},{" cho mọi tài khoản"," for all accounts"},
   {"Gỡ {0} ứng dụng Windows{1}?\r\n\r\n{2}\r\n\r\nGỡ bằng Remove-AppxPackage. Khôi phục: đăng ký lại từ thư mục gói nếu Windows còn giữ, hoặc cài lại từ Microsoft Store.","Remove {0} Windows apps{1}?\r\n\r\n{2}\r\n\r\nRemoval uses Remove-AppxPackage. Restore: re-register from the package folder if Windows still keeps it, or reinstall from Microsoft Store."},
   {"\r\n\r\nBỏ provisioning: tài khoản Windows tạo mới cũng sẽ không có ứng dụng này.","\r\n\r\nDeprovision: newly created Windows accounts will not get this app either."},
   {"{0} mục thuộc nhóm “Cần cân nhắc”:\r\n{1}\r\n\r\nĐây là thành phần hữu ích của Windows (ví dụ Microsoft Store dùng để cài lại app khác). Vẫn gỡ?","{0} items are in the “Use caution” group:\r\n{1}\r\n\r\nThese are useful Windows components (for example Microsoft Store is needed to reinstall other apps). Remove anyway?"},
   {"Đang gỡ ứng dụng Windows: ","Removing Windows app: "},{"Đã gỡ: ","Removed: "},{"Không gỡ được ","Could not remove "},{"Ứng dụng chưa gỡ","App not removed"},{"Đã gỡ {0} ứng dụng Windows; lỗi {1}.","Removed {0} Windows apps; {1} errors."},{"Kết quả gỡ ứng dụng Windows","Windows app removal result"},
   {"Chọn một ứng dụng trước.","Select an app first."},{"Thư mục gói không tồn tại hoặc không đọc được.","The package folder does not exist or cannot be read."},
   {"Gỡ được; cài lại từ Microsoft Store khi cần.","Removable; reinstall from Microsoft Store when needed."},{"Gỡ được nhưng nên cân nhắc: thành phần hữu ích của Windows hoặc cần để cài app khác.","Removable, but think twice: a useful Windows component or needed to install other apps."},
   {"Thư viện nền (framework) mà app khác phụ thuộc; Windows tự dọn khi không còn ai dùng.","Framework package other apps depend on; Windows removes it when nothing uses it."},{"Windows đánh dấu không thể gỡ.","Marked non-removable by Windows."},{"Thành phần cốt lõi của Windows (Start, Search, Settings, đăng nhập…); gỡ sẽ làm hỏng hệ thống.","Core Windows component (Start, Search, Settings, sign-in…); removing it breaks the system."},
   {"Không đọc được danh sách ứng dụng Windows: ","Could not read the Windows app list: "},{"Thành phần được bảo vệ, không gỡ: ","Protected component, not removed: "},{"Tên gói không hợp lệ: ","Invalid package name: "},{"Thư mục gói không hợp lệ: ","Invalid package folder: "},
   {"Đã gỡ gói; khôi phục = đăng ký lại từ thư mục gói nếu còn, hoặc cài lại từ Microsoft Store.","Package removed; restore = re-register from the package folder if present, or reinstall from Microsoft Store."},{"Đăng ký lại gói thất bại: ","Re-registering the package failed: "},{"Thư mục gói không còn; đã mở trang Microsoft Store của {0} để cài lại.","The package folder is gone; opened the Microsoft Store page of {0} to reinstall."},{"Không phải bản sao lưu ứng dụng Windows.","Not a Windows app backup."},
   {"Không tìm thấy Windows PowerShell; tính năng này chỉ chạy trên Windows.","Windows PowerShell not found; this feature runs on Windows only."},{"PowerShell không phản hồi trong thời gian cho phép.","PowerShell did not respond within the allowed time."},

   // Vault states and stubborn files
   {"{0} bản sao lưu ({1} trên đĩa)  •  Đã đánh dấu {2} ({3})  •  Khôi phục dùng dòng đang chọn; xóa vĩnh viễn dùng ô đánh dấu.","{0} backups ({1} on disk)  •  Marked {2} ({3})  •  Restore uses the selected row; permanent delete uses the checkboxes."},
   {"Đã sao lưu","Backed up"},{"Đã khôi phục","Restored"},{"Cần kiểm tra","Needs review"},{"Hẹn xóa khi khởi động lại","Delete at next reboot"},
   {"bỏ thuộc tính chỉ đọc/ẩn/hệ thống của {0} mục","cleared read-only/hidden/system on {0} entries"},{"chiếm quyền sở hữu và cấp toàn quyền cho Administrators","took ownership and granted Administrators full control"},
   {"{0} mục vẫn bị Windows chặn dù đã bỏ thuộc tính và chiếm quyền sở hữu (thường do một tiến trình đang giữ tệp):\r\n\r\n{1}\r\n\r\nHẹn xóa các mục này khi khởi động lại Windows? Chúng sẽ bị xóa thẳng lúc khởi động, KHÔNG có bản sao lưu để khôi phục.","Windows still blocks {0} items after clearing attributes and taking ownership (usually a process is holding the files):\r\n\r\n{1}\r\n\r\nSchedule them for deletion at the next Windows restart? They will be deleted directly at boot, with NO backup to restore."},
   {"Đã hẹn xóa khi khởi động lại: ","Scheduled for deletion at reboot: "},{"Vẫn bị chặn sau khi chiếm quyền sở hữu; có thể đang bị một tiến trình giữ. Đóng ứng dụng liên quan rồi thử lại.","Still blocked after taking ownership; a process may be holding it. Close the related application and try again."},

   // Junk cleaner runtime texts
   {"Bị khóa","Locked"},{"Chưa xem trước","Not previewed"},{"Không có gì để dọn","Nothing to clean"},{"Có thể dọn (chưa đủ)","Cleanable (partial)"},{"Có thể dọn","Cleanable"},
   {"{0} quy tắc  •  Đã chọn {1} nhóm, {2} tệp, {3}","{0} rules  •  Selected {1} groups, {2} files, {3}"},
   {"  •  XÓA THẲNG: không thể khôi phục","  •  DIRECT DELETE: cannot be undone"},{"  •  Chuyển vào Kho: chưa giải phóng dung lượng cho đến khi xóa vĩnh viễn trong kho","  •  Move to Vault: space is freed only after permanent deletion in the vault"},
   {"Xóa thẳng mục đã chọn","Delete selected directly"},{"Dọn mục đã chọn (vào kho)","Clean selected (to vault)"},
   {"Xem trước xong: {0} tệp, {1}","Preview done: {0} files, {1}"},{"  •  {0} nhóm bị khóa (di chuột lên dòng đỏ để xem lý do)","  •  {0} groups locked (hover a red row for the reason)"},
   {"Không có tệp rác đủ điều kiện theo quy tắc hiện tại.\r\nTệp mới hơn {0} giờ và tệp đang mở không được tính.","No junk matches the current rules.\r\nFiles newer than {0} hours and open files are not counted."},
   {"Đã dừng xem trước.","Preview stopped."},{"Xem trước rồi đánh dấu nhóm muốn dọn.","Preview first, then check the groups to clean."},
   {"XÓA THẲNG {0} tệp ({1}) mà KHÔNG lưu bản khôi phục?\r\n\r\n{2}\r\n\r\nThao tác này không thể hoàn tác. Chỉ tiếp tục khi chắc chắn các nhóm trên chỉ chứa bộ đệm/tệp tạm.","DELETE {0} files ({1}) DIRECTLY without a recovery copy?\r\n\r\n{2}\r\n\r\nThis cannot be undone. Continue only if you are sure the groups above hold nothing but caches/temporary files."},
   {"Xác nhận xóa vĩnh viễn","Confirm permanent deletion"},{"Xác nhận lần cuối: xóa thẳng {0} tệp, không có bản sao lưu?","Final confirmation: delete {0} files directly, with no backup?"},
   {"Chuyển {0} tệp ({1}) vào Kho khôi phục?\r\n\r\n{2}\r\n\r\nMỗi nhóm tạo một bản sao lưu; có thể khôi phục hoặc xóa vĩnh viễn sau trong tab Kho khôi phục. Dung lượng ổ đĩa chưa được giải phóng cho đến khi xóa vĩnh viễn.","Move {0} files ({1}) to the Recovery Vault?\r\n\r\n{2}\r\n\r\nEach group creates one backup; you can restore or permanently delete it later in the Recovery Vault tab. Disk space is freed only after permanent deletion."},
   {"Đang xóa thẳng…","Deleting directly…"},{"Đang chuyển vào kho…","Moving to vault…"},
   {"Đã xóa thẳng {0} tệp ({1}). Bỏ qua vì đang dùng: {2}. Lỗi: {3}.","Deleted {0} files directly ({1}). Skipped because in use: {2}. Errors: {3}."},
   {"Đã chuyển vào kho {0} tệp ({1}). Bỏ qua vì đang dùng: {2}. Lỗi: {3}.","Moved {0} files to the vault ({1}). Skipped because in use: {2}. Errors: {3}."},{" Bản sao lưu: {0}."," Backups: {0}."},
   {"\r\n\r\nLỗi đầu tiên:\r\n","\r\n\r\nFirst errors:\r\n"},{"\r\n\r\nCó thể khôi phục hoặc xóa vĩnh viễn trong tab Kho khôi phục.","\r\n\r\nYou can restore or permanently delete them in the Recovery Vault tab."},{"Kết quả dọn rác","Junk cleaning result"},
   {"Chọn một quy tắc để xem tệp.","Select a rule to view its files."},{"Tệp sẽ dọn — ","Files to clean — "},{"Sửa lần cuối","Last modified"},
   {"Hiển thị 2.000 tệp lớn nhất trong {0} tệp.","Showing the 2,000 largest of {0} files."},{"Chưa xem trước hoặc không có tệp đủ điều kiện.","Not previewed yet, or no file qualifies."},{"Danh sách chỉ để xem; chưa có gì bị thay đổi.","Read-only list; nothing has changed."},

   {"Không đọc được quy tắc dọn rác: ","Could not read junk rules: "},{"Đã nạp {0} quy tắc dọn rác từ {1}.","Loaded {0} junk rules from {1}."},{"Dọn rác: đang xem trước {0} quy tắc (chỉ đọc).","Junk: previewing {0} rules (read-only)."},
   {"Dọn rác: xem trước xong — {0} tệp, {1}, {2} nhóm bị khóa.","Junk: preview done — {0} files, {1}, {2} groups locked."},{"Dọn rác: bắt đầu xóa thẳng {0} tệp trong {1} nhóm.","Junk: deleting {0} files in {1} groups directly."},{"Dọn rác: bắt đầu chuyển vào kho {0} tệp trong {1} nhóm.","Junk: moving {0} files in {1} groups to the vault."},
   {"Dọn rác: ","Junk: "},{"Dọn rác lỗi: ","Junk error: "},
   // Junk rule groups and names (junk-rules.json)
   {"Hệ thống","System"},{"Trình duyệt","Browsers"},{"Bộ đệm","Caches"},{"Rác hệ thống (cần quyền quản trị)","System junk (administrator required)"},
   {"Tệp tạm của tài khoản (%TEMP%)","User temporary files (%TEMP%)"},{"Tệp tạm của Windows (C:\\Windows\\Temp)","Windows temporary files (C:\\Windows\\Temp)"},
   {"Tệp dump khi ứng dụng gặp lỗi (CrashDumps)","Application crash dumps (CrashDumps)"},{"Báo cáo lỗi Windows của tài khoản (WER)","User Windows Error Reporting (WER)"},
   {"Báo cáo lỗi Windows toàn máy (ProgramData\\WER)","Machine-wide Windows Error Reporting (ProgramData\\WER)"},{"Bộ đệm ảnh thu nhỏ của Explorer","Explorer thumbnail cache"},
   {"Google Chrome — bộ đệm","Google Chrome — cache"},{"Microsoft Edge — bộ đệm","Microsoft Edge — cache"},{"Brave — bộ đệm","Brave — cache"},{"Mozilla Firefox — bộ đệm","Mozilla Firefox — cache"},
   {"Bộ đệm web cũ của Windows (INetCache)","Legacy Windows web cache (INetCache)"},{"Bộ đệm shader của card đồ họa (DirectX / NVIDIA / AMD)","GPU shader cache (DirectX / NVIDIA / AMD)"},
   {"Gói Windows Update đã tải (SoftwareDistribution\\Download)","Downloaded Windows Update packages (SoftwareDistribution\\Download)"},{"Nhật ký bảo trì thành phần Windows (Logs\\CBS)","Component servicing logs (Logs\\CBS)"},
   {"Tệp dump lỗi hệ thống (Minidump, LiveKernelReports)","System crash dumps (Minidump, LiveKernelReports)"},{"Nhật ký cài đặt / nâng cấp Windows (Panther)","Windows setup / upgrade logs (Panther)"},
   {"Thành phần ActiveX/Java cũ (Downloaded Program Files)","Legacy ActiveX/Java components (Downloaded Program Files)"},
   // Junk rule descriptions
   {"Tệp tạm do ứng dụng để lại trong thư mục Temp của tài khoản hiện tại. Bỏ qua tệp mới hơn 24 giờ và tệp đang được mở.","Temporary files applications leave in the current user's Temp folder. Files newer than 24 hours and open files are skipped."},
   {"Thư mục Temp dùng chung của hệ thống. Cần quyền quản trị để đọc và dọn đầy đủ.","The shared system Temp folder. Administrator rights are needed to read and clean it fully."},
   {"Bản ghi bộ nhớ Windows tạo khi ứng dụng bị treo; chỉ hữu ích khi đang gỡ lỗi.","Memory dumps Windows writes when an application crashes; only useful while debugging."},
   {"Hàng đợi và kho báo cáo lỗi Windows Error Reporting trong hồ sơ người dùng.","Windows Error Reporting queue and archive in the user profile."},
   {"Hàng đợi báo cáo lỗi toàn máy. Cần quyền quản trị.","Machine-wide error report queue. Administrator rights required."},
   {"thumbcache_*.db và iconcache_*.db. Windows tạo lại khi cần; tệp đang được Explorer giữ sẽ bị bỏ qua.","thumbcache_*.db and iconcache_*.db. Windows rebuilds them on demand; files held open by Explorer are skipped."},
   {"Cache, Code Cache và GPUCache của mọi hồ sơ Chrome. Không đụng đến lịch sử, cookie, mật khẩu. Chỉ dọn khi Chrome đã đóng.","Cache, Code Cache and GPUCache of every Chrome profile. History, cookies and passwords are untouched. Cleaned only while Chrome is closed."},
   {"Cache, Code Cache và GPUCache của mọi hồ sơ Edge. Chỉ dọn khi Edge đã đóng (kể cả tiến trình nền).","Cache, Code Cache and GPUCache of every Edge profile. Cleaned only while Edge is closed (including background processes)."},
   {"Cache, Code Cache và GPUCache của mọi hồ sơ Brave. Chỉ dọn khi Brave đã đóng.","Cache, Code Cache and GPUCache of every Brave profile. Cleaned only while Brave is closed."},
   {"Thư mục cache2 của mọi hồ sơ Firefox. Không đụng đến lịch sử, cookie, mật khẩu. Chỉ dọn khi Firefox đã đóng.","The cache2 folder of every Firefox profile. History, cookies and passwords are untouched. Cleaned only while Firefox is closed."},
   {"Cache của Internet Explorer / WebView / Office web content. Không chứa mật khẩu hay lịch sử.","Cache of Internet Explorer / WebView / Office web content. Holds no passwords or history."},
   {"Shader đã biên dịch; trình điều khiển tự tạo lại khi cần. Game có thể giật nhẹ ở lần chạy đầu sau khi dọn.","Compiled shaders; the driver rebuilds them on demand. Games may stutter briefly on the first run after cleaning."},
   {"Bộ cài cập nhật Windows đã tải về và đã áp dụng. Windows tự tải lại nếu cần. Chỉ dọn tệp cũ hơn 7 ngày để không cắt ngang cập nhật đang chạy.","Downloaded and already-applied Windows Update packages. Windows re-downloads them if needed. Only files older than 7 days are cleaned so a running update is never interrupted."},
   {"Nhật ký của Component Based Servicing, có thể phình tới nhiều GB. Chỉ dọn tệp cũ hơn 7 ngày; nhật ký hiện tại được giữ.","Component Based Servicing logs, which can grow to several GB. Only files older than 7 days are cleaned; the current log is kept."},
   {"Bản ghi bộ nhớ Windows tạo khi màn hình xanh hoặc lỗi kernel; chỉ cần khi đang gỡ lỗi.","Memory dumps Windows writes after a blue screen or kernel error; only needed while debugging."},
   {"Nhật ký do trình cài đặt Windows để lại sau khi nâng cấp phiên bản. Chỉ dọn tệp cũ hơn 7 ngày.","Logs left by Windows Setup after a version upgrade. Only files older than 7 days are cleaned."},
   {"Thư mục kế thừa của Internet Explorer; hầu như luôn trống hoặc chỉ còn tàn dư.","Legacy Internet Explorer folder; almost always empty or holding remnants only."},
   // Network tab: application view
   {"Hoạt động","Activity"},{"Kết nối","Connections"},{"Đã kết nối","Established"},{"Lắng nghe","Listening"},{"kết nối","connections"},
   {"Đang gửi","Sending"},{"Đang nhận","Receiving"},{"Gửi và nhận","Sending and receiving"},{"Không hoạt động","Idle"},{"Gửi đi","Out"},{"Nhận về","In"},
   {"Hiện tất cả kết nối","Show all connections"},{"Kết nối của tất cả ứng dụng — bấm một ứng dụng ở bảng trên để lọc","Connections of all applications — click an application above to filter"},{"Kết nối của: {0}","Connections of: {0}"},
   {"Chọn một ứng dụng ở bảng trên để xem các kết nối của nó.","Select an application above to see its connections."},{"Ứng dụng đã chọn không còn kết nối nào.","The selected application has no connections left."},
   {"Mạng: không tự bật được băng thông (ETW) — {0}","Network: could not auto-start bandwidth (ETW) — {0}"},
   {"Đường dẫn:","Path:"},{"không đọc được (tiến trình được bảo vệ hoặc đã kết thúc)","unreadable (protected process or already exited)"},{"Nhà phát hành (chữ ký):","Publisher (signature):"},
   {"{0} kết nối • {1} đã kết nối • {2} lắng nghe • {3} máy từ xa","{0} connections • {1} established • {2} listening • {3} remote hosts"},{"Gửi {0} ({1}) • Nhận {2} ({3})","Sent {0} ({1}) • Received {2} ({3})"},
   {"Tweek Pro chỉ hiển thị; không chặn hay thay đổi kết nối.","Tweek Pro only displays; it never blocks or changes connections."},{"Chi tiết ứng dụng","Application details"},
   {"Đang lắng nghe","Listening"},{"Đã đóng","Closed"},{"Đang đóng","Closing"},{"SYN đã gửi","SYN sent"},{"SYN đã nhận","SYN received"},
   {"{0} kết nối hiển thị / {1} tổng  •  {2} tiến trình","{0} connections shown / {1} total  •  {2} processes"},{"Đã tạm dừng làm mới","Refresh paused"},{"Làm mới mỗi {0} giây","Refreshing every {0} s"},
   {"ETW: {0} sự kiện","ETW: {0} events"},{", mất {0}",", {0} lost"},{"Tổng","Total"},{"Băng thông: chưa bật","Bandwidth: off"},
   // Network tab: end process / stop service
   {"Dịch vụ","Service"},{"Chỉ hỗ trợ trên Windows.","Windows only."},{"Tiến trình đã kết thúc.","The process has already exited."},
   {"Tiến trình cốt lõi của Windows — không thể kết thúc.","Core Windows process — cannot be ended."},{"Đây là Tweek Pro.","This is Tweek Pro itself."},
   {"svchost.exe chứa nhiều dịch vụ Windows — hãy dừng từng dịch vụ bên trong thay vì kết thúc tiến trình.","svchost.exe hosts several Windows services — stop the individual services instead of ending the process."},
   {"Không đủ quyền để kết thúc tiến trình này (tiến trình được bảo vệ).","Not allowed to end this process (protected process)."},{"Windows từ chối kết thúc tiến trình này.","Windows refused to end this process."},{"Tiến trình chưa kết thúc sau 8 giây.","The process did not exit within 8 seconds."},
   {"{0} là dịch vụ cốt lõi của Windows — không dừng.","{0} is a core Windows service — not stopped."},{"Tên dịch vụ không hợp lệ.","Invalid service name."},{"Dịch vụ không cho phép dừng (CanStop=false).","The service does not accept stop requests (CanStop=false)."},
   {"Đã dừng và vô hiệu hóa; khôi phục = đặt lại kiểu khởi động {0} và chạy lại dịch vụ.","Stopped and disabled; restore = set start mode back to {0} and start the service."},{"Không dừng được dịch vụ {0}: {1}","Could not stop service {0}: {1}"},
   {"Không phải bản sao lưu dịch vụ.","Not a service backup."},{"Đã đặt lại kiểu khởi động nhưng chưa chạy được dịch vụ: {0}","Start mode restored but the service could not be started: {0}"},
   {"Kết thúc tiến trình {0} (PID {1})","End process {0} (PID {1})"},{"Kết thúc tiến trình {0} (PID {1})?\r\nỨng dụng sẽ đóng ngay và dữ liệu chưa lưu có thể mất. Nếu đây là dịch vụ, Windows có thể tự chạy lại nó — dùng \"Dừng và vô hiệu hóa\" để ngăn.","End process {0} (PID {1})?\r\nThe application closes immediately and unsaved data may be lost. If it is a service, Windows may restart it — use \"Stop and disable\" to prevent that."},
   {"Mạng: đã kết thúc {0} (PID {1}).","Network: ended {0} (PID {1})."},{"Dịch vụ Windows trong tiến trình này ({0})","Windows services in this process ({0})"},{"dịch vụ cốt lõi","core service"},
   {"Dừng dịch vụ: {0}","Stop service: {0}"},{"Dừng và vô hiệu hóa: {0}","Stop and disable: {0}"},
   {"Dừng dịch vụ {0}?\r\nDịch vụ sẽ chạy lại theo kiểu khởi động hiện tại ({1}) ở lần khởi động máy sau.","Stop service {0}?\r\nIt will start again according to its current start mode ({1}) at the next boot."},
   {"Dừng và vô hiệu hóa dịch vụ {0}?\r\nDịch vụ không tự chạy lại nữa. Kiểu khởi động cũ ({1}) được lưu vào Kho khôi phục để bật lại bất kỳ lúc nào.","Stop and disable service {0}?\r\nIt will no longer start on its own. The previous start mode ({1}) is saved in the Recovery Vault so you can re-enable it any time."},
   {"Mạng: đã dừng dịch vụ {0}.","Network: stopped service {0}."},{"Mạng: đã dừng và vô hiệu hóa dịch vụ {0}; bật lại trong Kho khôi phục.","Network: stopped and disabled service {0}; re-enable it from the Recovery Vault."},
   {"Mở thư mục chứa tệp","Open file location"},{"Sao chép đường dẫn","Copy path"},
   // Right-click menus on lists
   {"Gỡ ứng dụng này","Uninstall this application"},{"Quét phần còn sót của ứng dụng này","Scan this application's leftovers"},{"Mở thư mục cài","Open install folder"},{"chưa khai báo thư mục cài","no install folder declared"},
   {"Sao chép thư mục cài","Copy install folder"},{"Sao chép lệnh gỡ","Copy uninstall command"},{"Bỏ đánh dấu tất cả","Uncheck all"},{"Đường dẫn không còn tồn tại: ","Path no longer exists: "},
   {"Gỡ gói này","Remove this package"},{"thành phần được bảo vệ","protected component"},{"Sao chép tên gói","Copy package name"},
   {"Tắt mục khởi động (sao lưu)","Disable startup entry (backed up)"},{"đã nằm trong kho","already in the vault"},{"vẫn đang có đăng ký","still registered"},{"Sao chép lệnh","Copy command"},
   {"Khôi phục mục này","Restore this item"},{"đã khôi phục","already restored"},{"Xóa vĩnh viễn mục này","Delete this item permanently"},{"Mở thư mục sao lưu","Open backup folder"},{"Mở vị trí gốc","Open original location"},{"Sao chép đường dẫn gốc","Copy original path"},
   // Services tab
   {"Dịch vụ hệ thống","Services"},{"Đang chạy","Running"},{"Tất cả","All"},{"Bên thứ ba","Third-party"},{"Có thể tắt","Safe to disable"},{"Đã dừng","Stopped"},{"Hiện","Show"},
   {"Kiểu khởi động","Start mode"},{"RAM","RAM"},{"Có dừng được?","Can I stop it?"},{"Nhóm","Group"},{"Giải thích","What it does"},
   {"Dừng","Stop"},{"Dừng và vô hiệu hóa","Stop and disable"},{"Services của Windows","Windows Services"},
   {"Mỗi dịch vụ được giải thích bằng lời thường: nó làm gì, thuộc Windows hay ứng dụng nào cài, và có dừng được không. Dịch vụ cốt lõi bị khóa. \"Dừng và vô hiệu hóa\" lưu kiểu khởi động cũ vào Kho khôi phục để bật lại. Chuột phải lên một dòng để thao tác.","Every service is explained in plain words: what it does, whether it belongs to Windows or to an app you installed, and whether you can stop it. Core services are locked. \"Stop and disable\" saves the old start mode to the Recovery Vault so you can re-enable it. Right-click a row to act."},
   {"Chọn một dịch vụ để xem giải thích đầy đủ và lời khuyên có nên dừng hay không.","Select a service to see the full explanation and advice on whether to stop it."},
   {"Chưa tải danh sách.\r\nBấm Tải danh sách để đọc các dịch vụ Windows (WMI). Chỉ đọc; chưa có gì bị thay đổi.","Not loaded yet.\r\nClick Load list to read Windows services (WMI). Read-only; nothing has been changed."},
   {"Đang đọc dịch vụ qua WMI…","Reading services through WMI…"},{"Không đọc được danh sách dịch vụ: ","Could not read the service list: "},
   {"Dịch vụ: {0} dịch vụ, {1} đang chạy, {2} của bên thứ ba.","Services: {0} services, {1} running, {2} third-party."},
   {"Tự động","Automatic"},{"Thủ công","Manual"},{"Đã vô hiệu","Disabled"},{"Khi khởi động","Boot"},{"Đang khởi động","Starting"},{"Đang dừng","Stopping"},
   {"Không đọc được dịch vụ nào.","No services could be read."},{"Không có dịch vụ khớp bộ lọc.","No service matches the filter."},
   {"{0} dịch vụ đang hiện / {1} dịch vụ, {2} đang chạy  •  {3} cốt lõi (khóa), {4} Windows, {5} tùy chọn, {6} bên thứ ba","{0} shown / {1} services, {2} running  •  {3} core (locked), {4} Windows, {5} optional, {6} third-party"},
   {"Khởi động: ","Start mode: "},{"Nó làm gì: ","What it does: "},{"Có dừng được không? ","Can I stop it? "},{"Nhà phát hành: ","Publisher: "},{"không rõ","unknown"},{"Tệp: ","File: "},{"Tài khoản: ","Account: "},{"Windows mô tả: ","Windows description: "},
   {"Chi tiết dịch vụ","Service details"},{"Chọn một dịch vụ.","Select a service."},
   {"Dịch vụ cốt lõi của Windows — Tweek Pro không dừng dịch vụ này.","Core Windows service — Tweek Pro will not stop it."},
   {"Dừng và vô hiệu hóa dịch vụ {0}?\r\n\r\n{1}\r\n\r\nDịch vụ không tự chạy lại nữa. Kiểu khởi động cũ ({2}) được lưu vào Kho khôi phục để bật lại bất kỳ lúc nào.","Stop and disable service {0}?\r\n\r\n{1}\r\n\r\nIt will no longer start on its own. The old start mode ({2}) is saved to the Recovery Vault so you can re-enable it any time."},
   {"Dừng dịch vụ {0}?\r\n\r\n{1}\r\n\r\nDịch vụ sẽ chạy lại theo kiểu khởi động hiện tại ({2}) ở lần khởi động máy sau.","Stop service {0}?\r\n\r\n{1}\r\n\r\nIt will start again according to its current start mode ({2}) at the next boot."},
   {"Dịch vụ: đã dừng và vô hiệu hóa {0}; bật lại trong Kho khôi phục.","Services: stopped and disabled {0}; re-enable from the Recovery Vault."},{"Dịch vụ: đã dừng {0}.","Services: stopped {0}."},
   {"Dịch vụ này đang chạy.","This service is already running."},{"Dịch vụ: đã khởi động {0}.","Services: started {0}."},
   {"Khởi động lại dịch vụ {0}?\r\nDịch vụ dừng rồi chạy lại ngay; kết nối đang mở của nó sẽ bị ngắt trong giây lát.","Restart service {0}?\r\nIt stops and starts again immediately; its open connections drop for a moment."},
   {"Dịch vụ: đã khởi động lại {0}.","Services: restarted {0}."},
   {"Dừng dịch vụ","Stop service"},{"Khởi động dịch vụ","Start service"},{"Khởi động lại dịch vụ","Restart service"},{"Dừng và vô hiệu hóa (lưu vào Kho)","Stop and disable (saved to Vault)"},
   {"đã dừng","stopped"},{"đang chạy","running"},{"đã vô hiệu — bật lại trong Kho khôi phục","disabled — re-enable from the Recovery Vault"},{"đã vô hiệu","disabled"},{"không có tiến trình","no process"},
   {"Kết thúc tiến trình (PID {0})","End process (PID {0})"},{"Dịch vụ: đã kết thúc tiến trình PID {0} của {1}.","Services: ended process PID {0} of {1}."},
   {"Sao chép tên dịch vụ","Copy service name"},
   {"(dịch vụ theo tài khoản; Windows tự tạo lại khi đăng nhập)","(per-user service; Windows recreates it at sign-in)"},
   {"Thành phần của Windows (chạy từ thư mục Windows). Không có mô tả thêm.","Windows component (runs from the Windows folder). No further description."},
   {"Dịch vụ nền của {0}. Ứng dụng cài kèm để chạy ngầm dù bạn chưa mở nó; dừng thường an toàn, ứng dụng sẽ tự bật lại khi cần.","Background service of {0}. Installed alongside the app to run even when the app is closed; usually safe to stop, the app restarts it when needed."},
   {"Cốt lõi — không dừng","Core — do not stop"},{"Windows — dừng khi hiểu rõ","Windows — stop only if you know why"},{"Tùy chọn — tắt được nếu không dùng","Optional — disable if unused"},{"Bên thứ ba — dừng an toàn","Third-party — safe to stop"},
   {"Windows cần dịch vụ này để chạy ổn định; Tweek Pro không cho dừng hay vô hiệu hóa.","Windows needs this service to run reliably; Tweek Pro does not allow stopping or disabling it."},
   {"Thuộc Windows nhưng không thiết yếu. Dừng có thể làm mất một tính năng; vô hiệu hóa được lưu vào Kho để bật lại.","Part of Windows but not essential. Stopping may lose a feature; disabling is saved to the Vault so you can re-enable it."},
   {"Tính năng tùy chọn của Windows. Nếu bạn không dùng, tắt an toàn để tiết kiệm RAM và thời gian khởi động.","Optional Windows feature. If you do not use it, disabling is safe and saves RAM and boot time."},
   {"Do ứng dụng bên thứ ba cài. Dừng an toàn; nếu vô hiệu hóa, ứng dụng đó có thể mất cập nhật tự động.","Installed by a third-party app. Safe to stop; if disabled, that app may lose automatic updates."},
   {"Bảo mật","Security"},{"Cập nhật","Updates"},{"Màn hình & âm thanh","Display & audio"},{"Tùy chọn","Optional"},{"Quyền riêng tư","Privacy"},{"Game","Games"},{"Máy chủ","Server"},{"Điều khiển từ xa","Remote control"},{"Thiết bị ngoại vi","Peripherals"},{"Bản quyền","Licensing"},{"Phụ trợ","Helper"},
   // AI assistant tab
   {"Trợ lý AI","AI Assistant"},{"Nhà cung cấp","Provider"},{"Lưu khóa","Save key"},{"Kiểm tra kết nối","Test connection"},
   {"Điểm cuối API (tùy chọn, cho máy chủ tương thích)","API endpoint (optional, for compatible servers)"},
   {"Cho phép AI thực hiện thao tác thay đổi (mỗi lần đều hỏi xác nhận)","Allow the AI to perform system-changing actions (each one asks for confirmation)"},
   {"Khóa API được mã hóa bằng Windows DPAPI theo tài khoản của bạn và chỉ gửi tới nhà cung cấp bạn chọn. AI đọc dữ liệu qua các công cụ chỉ đọc; mọi thao tác thay đổi (dừng dịch vụ, kết thúc tiến trình, tắt khởi động, gỡ ứng dụng) đều hiện hộp xác nhận và tuân thủ các giới hạn an toàn của Tweek Pro.","The API key is encrypted with Windows DPAPI for your account and only sent to the provider you choose. The AI reads data through read-only tools; every system-changing action (stop service, end process, disable startup, uninstall) shows a confirmation dialog and follows Tweek Pro's safety limits."},
   {"Máy tôi có gì đang chạy nền tốn RAM và tắt được không?","What is running in the background eating RAM, and can I turn it off?"},
   {"Dịch vụ nào của bên thứ ba có thể dừng an toàn?","Which third-party services are safe to stop?"},
   {"Ứng dụng nào đang dùng mạng nhiều nhất?","Which application is using the network the most?"},
   {"Có bao nhiêu rác có thể dọn?","How much junk can be cleaned?"},{"Mục khởi động nào nên tắt?","Which startup entries should I disable?"},
   {"Gửi","Send"},{"Xóa hội thoại","Clear chat"},{"Chưa lưu khóa.","No key saved."},{"Đã lưu (mã hóa DPAPI): ","Saved (DPAPI encrypted): "},{"Đã lưu (chỉ mã hóa base64 — ngoài Windows): ","Saved (base64 only — outside Windows): "},
   {"Sẵn sàng — {0}, model {1}. Enter để gửi; Shift+Enter xuống dòng.","Ready — {0}, model {1}. Enter sends; Shift+Enter adds a line."},
   {"Nhập API key của Anthropic (Claude) hoặc OpenAI (GPT/Codex) rồi bấm Lưu khóa để bắt đầu.","Enter an Anthropic (Claude) or OpenAI (GPT/Codex) API key and click Save key to begin."},
   {"Trợ lý AI: đã xóa API key.","AI assistant: API key removed."},{"Trợ lý AI: đã lưu khóa cho {0} ({1}).","AI assistant: key saved for {0} ({1})."},
   {"Chưa nhập API key.","No API key entered."},{"API key chứa khoảng trắng hoặc ký tự lạ — hãy dán lại.","The API key contains whitespace or unusual characters — paste it again."},
   {"Key của Anthropic bắt đầu bằng sk-ant-.","Anthropic keys start with sk-ant-."},{"Key của OpenAI bắt đầu bằng sk-.","OpenAI keys start with sk-."},
   {" API key không hợp lệ hoặc đã bị thu hồi."," The API key is invalid or revoked."},{" Hết hạn mức hoặc gửi quá nhanh — thử lại sau."," Quota exhausted or rate limited — try again later."},{" Tên model không tồn tại — kiểm tra ô Model."," Unknown model name — check the Model box."},
   {"Đang kiểm tra kết nối…","Testing connection…"},{"Kết nối thành công — model trả lời: \"{0}\" ({1} token vào / {2} ra).","Connected — the model replied \"{0}\" ({1} tokens in / {2} out)."},
   {"Trợ lý AI: kiểm tra kết nối thành công.","AI assistant: connection test succeeded."},{"Kết nối thất bại: ","Connection failed: "},{"Trợ lý AI: kết nối thất bại — ","AI assistant: connection failed — "},
   {"Xin chào! Tôi là trợ lý của Tweek Pro. Hỏi tôi về máy này — ứng dụng, dịch vụ, mạng, rác, khởi động — hoặc nhờ tôi thao tác; mọi thay đổi đều hỏi bạn xác nhận trước.","Hello! I am Tweek Pro's assistant. Ask me about this PC — applications, services, network, junk, startup — or ask me to act; every change asks you for confirmation first."},
   {"Đang hỏi model…","Asking the model…"},{"Xong — {0} token vào / {1} ra trong phiên này.","Done — {0} tokens in / {1} out this session."},{"Lỗi: ","Error: "},{"Trợ lý AI: ","AI assistant: "},
   {"Bạn","You"},{"Công cụ AI","Tool"},{"Lỗi","Error"},
   {"Trợ lý AI muốn thực hiện:\r\n\r\n{0}\r\n\r\nCho phép? Tweek Pro vẫn áp dụng mọi giới hạn an toàn (dịch vụ/tiến trình cốt lõi bị từ chối, thay đổi được lưu vào Kho khôi phục khi có thể).","The AI assistant wants to run:\r\n\r\n{0}\r\n\r\nAllow it? Tweek Pro still enforces every safety limit (core services/processes are refused, changes are saved to the Recovery Vault when possible)."},
   {"Trợ lý đã gọi công cụ quá nhiều vòng và dừng lại. Hãy hỏi cụ thể hơn.","The assistant called tools for too many rounds and stopped. Please ask something more specific."},
   {"công cụ không tồn tại","unknown tool"},{"bị chặn — thao tác thay đổi đang tắt","blocked — system-changing actions are off"},{"người dùng từ chối","declined by the user"},{"xong","done"},{"lỗi","error"},
   {"Trợ lý AI: đã {0} dịch vụ {1}.","AI assistant: {0} service {1}."},{"dừng và vô hiệu hóa","stopped and disabled"},{"dừng","stopped"},
   {"Trợ lý AI: đã khởi động dịch vụ {0}.","AI assistant: started service {0}."},{"Trợ lý AI: đã kết thúc tiến trình {0} (PID {1}).","AI assistant: ended process {0} (PID {1})."},{"Trợ lý AI: đã tắt mục khởi động {0}.","AI assistant: disabled startup entry {0}."},
   {"Có 4 dịch vụ bên thứ ba đang chạy, dừng đều an toàn:\r\n• Adobe Acrobat Update Service (AdobeARMservice) — 3 MB, trình cập nhật; Acrobat vẫn tự cập nhật khi mở.\r\n• MySQL80 — 412 MB RAM, máy chủ cơ sở dữ liệu; dừng nếu bạn không đang lập trình.\r\n• Zoom Sharing Service (ZoomCptService) — 12 MB, Zoom tự bật lại khi cần.\r\n• Brave Elevation Service — đã dừng, chỉ chạy khi cập nhật.\r\nBạn muốn tôi dừng MySQL80 để giải phóng 412 MB không? Tôi sẽ hỏi xác nhận trước khi làm.","4 third-party services are running and all are safe to stop:\r\n• Adobe Acrobat Update Service (AdobeARMservice) — 3 MB, an updater; Acrobat still updates itself when opened.\r\n• MySQL80 — 412 MB RAM, a database server; stop it when you are not developing.\r\n• Zoom Sharing Service (ZoomCptService) — 12 MB, Zoom restarts it when needed.\r\n• Brave Elevation Service — already stopped, runs only during updates.\r\nShall I stop MySQL80 to free 412 MB? I will ask for confirmation first."},
   // Applications tab details
   {"Toàn máy","All users"},{"Tài khoản","This account"},{"Không rõ","Unknown"},{"{0} ứng dụng hiển thị  /  {1} ứng dụng trên máy","{0} shown  /  {1} installed"},
   {"Chọn một ứng dụng để xem thông tin.","Select an application to see its details."},{"Chọn một ứng dụng để xem thông tin. Dùng ô tìm kiếm để lọc theo tên hoặc nhà phát hành.","Select an application to see its details. Use the search box to filter by name or publisher."},
   {"Thư mục: ","Folder: "},{"Chưa được ứng dụng khai báo","Not declared by the application"},{"Ngày do bộ cài cung cấp, có thể là ngày cập nhật. Giá trị gốc: ","Date reported by the installer; may be the last update. Raw value: "},{"không có","none"},
   {"Mở trình gỡ chính thức lần lượt cho {0} ứng dụng?\r\n\r\n{1}\r\n\r\nTrình gỡ có thể xóa dữ liệu và yêu cầu quyền quản trị. Kho Tweek Pro chỉ khôi phục phần dọn sau đó, không hoàn tác trình gỡ.","Open the official uninstaller for {0} application(s), one after another?\r\n\r\n{1}\r\n\r\nThe uninstaller may delete data and ask for administrator rights. Tweek Pro's vault only restores the cleanup done afterwards; it cannot undo the uninstaller."},
   {"Tiếp tục gỡ {0}?\r\nChọn No để dừng hàng đợi.","Continue uninstalling {0}?\r\nChoose No to stop the queue."},
   // Review fixes
   {"Không kết nối được tới máy chủ API: ","Could not reach the API server: "},{"Máy chủ API không trả lời trong 120 giây.","The API server did not answer within 120 seconds."},
   {"Điểm cuối API không phải URL hợp lệ.","The API endpoint is not a valid URL."},{"Điểm cuối API phải dùng https:// (http:// chỉ cho localhost) để không lộ khóa.","The API endpoint must use https:// (http:// only for localhost) so the key is not exposed."},
   {"Model không trả lời nội dung nào","The model returned no content"},{"Trợ lý AI: không mã hóa được khóa bằng DPAPI — ","AI assistant: could not encrypt the key with DPAPI — "},
   {"Windows không mã hóa được khóa (DPAPI). Khóa chưa được lưu.","Windows could not encrypt the key (DPAPI). The key was not saved."},{"không xác định được tiến trình","process name unknown"},
   {"Chưa được ứng dụng khai báo thư mục cài","Install folder not declared by the application"},{"Ngày bộ cài khai báo: ","Date reported by the installer: "},{"Không có","None"},{"không phải đường dẫn tệp","not a file path"},
   {" (MSI im lặng)"," (silent MSI)"},
   {"API key (không cần)","API key (optional)"},
   {"Chưa chọn model cục bộ — bấm \"Tải danh sách model\" rồi chọn một model đã nạp trong LM Studio/Ollama.","No local model selected. Click \"Load models\" and select a model loaded in LM Studio/Ollama."},
   {"Chưa chọn model cục bộ.","No local model selected."},
   {"Chỉ máy chủ tương thích OpenAI mới hỗ trợ liệt kê model.","Only OpenAI-compatible servers support listing models."},
   {"Chỉ đọc — không thay đổi gì","Read only — no changes"},
   {"Chọn LM Studio/Ollama để dùng model cục bộ, hoặc Claude/OpenAI bằng API key. Dữ liệu gửi tới máy chủ bạn chọn. Kho khôi phục lưu phần dọn còn sót, không hoàn tác trình gỡ ứng dụng. Chế độ Tự động chỉ dùng khi bạn chọn; giới hạn bảo vệ hệ thống luôn có hiệu lực.","Choose LM Studio/Ollama for local models, or Claude/OpenAI with an API key. Data goes to your selected server. The vault backs up leftover cleanup, not the official uninstall. Automatic mode requires your selection; system protections always apply."},
   {"Hỏi xác nhận trước mỗi thao tác","Confirm each action"},
   {"Không bao giờ xóa gốc ổ đĩa.","Drive roots can never be removed."},
   {"Không kết nối được tới máy chủ LLM cục bộ — hãy mở LM Studio/Ollama và bật Local Server: ","Cannot reach the local LLM server. Open LM Studio/Ollama and enable its server: "},
   {"Không tải được danh sách model: ","Could not load models: "},
   {"Lưu cấu hình","Save settings"},
   {"Model cục bộ: ","Local model: "},
   {"Máy chủ API không trả lời trong {0} giây.","The API server did not respond within {0} seconds."},
   {"Máy chủ LLM cục bộ phải nằm ở localhost hoặc trong mạng nội bộ (10.x, 172.16–31.x, 192.168.x).","The local LLM server must use localhost or a private network address (10.x, 172.16–31.x, 192.168.x)."},
   {"Máy chủ không có model nào — hãy nạp (load) một model trong LM Studio hoặc `ollama pull` trước.","No models found. Load a model in LM Studio or use `ollama pull` first."},
   {"Mở LM Studio/Ollama, nạp một model, bấm \"Tải danh sách model\" rồi chọn model và Lưu cấu hình.","Open LM Studio/Ollama, load a model, click \"Load models\", select it and save settings."},
   {"Nhập API key của Anthropic (Claude) hoặc OpenAI (GPT/Codex) rồi bấm Lưu cấu hình để bắt đầu. Hoặc chọn LM Studio/Ollama để dùng model trên máy, không cần key.","Enter an Anthropic (Claude) or OpenAI (GPT/Codex) API key and save settings. Or choose LM Studio/Ollama to use a local model without a key."},
   {"Nằm trong thư mục Windows (System32, WinSxS…) — Tweek Pro không bao giờ xóa.","Inside the Windows directory (System32, WinSxS…). Tweek Pro never removes this."},
   {"Quyền thao tác của AI","AI action permissions"},
   {"Sẵn sàng — {0}, model {1}, chế độ: {2}. Enter để gửi; Shift+Enter xuống dòng.","Ready — {0}, model {1}, mode: {2}. Enter to send; Shift+Enter for a new line."},
   {"Trợ lý AI: chưa dọn được ","AI assistant: could not clean "},
   {"Trợ lý AI: dọn rác {0} quy tắc vào Kho khôi phục.","AI assistant: cleaning {0} junk rules into the Recovery Vault."},
   {"Trợ lý AI: mở trình gỡ {0}{1}.","AI assistant: opening the uninstaller for {0}{1}."},
   {"Trợ lý AI: quét phần còn sót của {0} ứng dụng ({1}).","AI assistant: scanning leftovers for {0} applications ({1})."},
   {"Trợ lý AI: từ chối xóa ","AI assistant: refused to remove "},
   {"Trợ lý AI: đã lưu cấu hình {0}, model {1}, chế độ {2}.","AI assistant: saved {0}, model {1}, mode {2}."},
   {"Trợ lý AI: đã sao lưu và dọn ","AI assistant: backed up and cleaned "},
   {"Tải danh sách model","Load models"},
   {"Tự động thực hiện, không hỏi lại","Automatic actions, without asking again"},
   {"Xin chào! Tôi là trợ lý của Tweek Pro. Hỏi tôi về máy này hoặc ra lệnh trực tiếp — \"gỡ Zoom và dọn sạch phần còn sót\", \"kill dịch vụ MySQL\", \"dọn rác\" — tôi sẽ làm ngay và báo lại kết quả. Phần dọn còn sót được sao lưu; kho không hoàn tác trình gỡ chính thức; thư mục Windows/System32 luôn được bảo vệ.","Hello! I am the Tweek Pro assistant. Ask about this PC or give an instruction such as \"uninstall Zoom and clean its leftovers\", \"stop MySQL\" or \"clean junk\". I will act and report the result. Leftover cleanup is backed up; the vault cannot undo the official uninstall. Windows/System32 remain protected."},
   {"\"{0}\" là thư mục gốc hệ thống/người dùng, không được xóa.","\"{0}\" is a system/user root folder and cannot be removed."},
   {"quét nhanh","quick scan"},
   {"quét sâu","deep scan"},
   {"tự động thực hiện","running automatically"},
   {"vẫn còn đăng ký cài đặt; không tự quét/dọn.","still registered as installed; automatic scan/cleanup skipped."},
   {"Đang tải danh sách model…","Loading models…"},
   {"Đi qua thư mục hệ thống \"{0}\" — bị chặn.","Path passes through system folder \"{0}\" — blocked."},
   {"Điểm cuối API","API endpoint"},
   {"Đã tải {0} model từ {1}. Chọn model rồi bấm Lưu cấu hình.","Loaded {0} models from {1}. Select a model and save settings."},
   {"Đường dẫn không hợp lệ hoặc không phải đường dẫn tuyệt đối trên ổ đĩa.","Invalid path or not an absolute drive path."},
   {"Đường dẫn trống.","Empty path."},
   {"đã bỏ đăng ký.","no longer registered."},
   {"Model này không hỗ trợ thao tác. Hãy chọn model có hỗ trợ gọi công cụ.","This model cannot perform actions. Select a model with tool-calling support."},
   {"Model này không hỗ trợ gọi công cụ; chỉ trả lời hướng dẫn, không thao tác trên máy.","This model does not support tool calling. It can give guidance but cannot operate this PC."},
   // Applications / Leftovers / Vault / Log tab runtime texts (App.cs, Presentation.cs)
   {"LỖI: ","ERROR: "},{"Đã lưu settings.json.","settings.json saved."},{"Không đọc được lịch sử: ","Could not read history: "},
   {"Nhật ký phiên hiện tại. Tệp nhật ký xoay vòng theo ngày trong {0} (giữ {1} ngày). Cài đặt: {2}.","Current session log. Log files rotate daily in {0} (kept {1} days). Settings: {2}."},
   {"Đang xử lý. Hãy chờ thao tác hiện tại hoàn tất.","Working. Please wait for the current operation to finish."},
   {"Không đọc được danh sách ứng dụng","Could not read the application list"},
   {"Không đọc được danh sách ứng dụng.\r\n{0}\r\n\r\nBấm Làm mới để thử lại. Nếu khóa HKLM bị chặn, chạy Tweek Pro với quyền quản trị cùng tài khoản Windows.","Could not read the application list.\r\n{0}\r\n\r\nClick Refresh to try again. If the HKLM key is blocked, run Tweek Pro as administrator with the same Windows account."},
   {"Không có ứng dụng khớp với «{0}».\r\nThử từ khóa khác hoặc xóa ô tìm kiếm.","No application matches «{0}».\r\nTry another keyword or clear the search box."},
   {"Đã đọc {0} ứng dụng desktop. Chưa bao gồm toàn bộ ứng dụng Microsoft Store.","Read {0} desktop applications. Microsoft Store apps are not fully included."},
   {"Chọn ứng dụng muốn gỡ.","Select the application(s) to uninstall."},{"Mở trình gỡ: ","Opening uninstaller: "},
   {"Trình gỡ của {0} đã kết thúc tiến trình chính nhưng ứng dụng vẫn còn đăng ký. Nếu có cửa sổ gỡ khác, hãy hoàn tất hoặc hủy rồi nhấn OK. Nếu cần khởi động lại, có thể quét lại lịch sử sau đó.","The uninstaller of {0} ended its main process but the application is still registered. If another uninstall window is open, finish or cancel it, then press OK. If a restart is required, you can rescan the history later."},
   {"Kiểm tra trình gỡ","Uninstaller check"},{"đã bỏ đăng ký; mở cửa sổ quét phần còn sót.","registration removed; opening the leftover scan window."},
   {"Không hoàn tất thao tác","Operation not completed"},{"Đã kết thúc hàng đợi. Còn {0} mục chờ duyệt ở tab Phần còn sót.","Queue finished. {0} items await review in the Leftovers tab."},
   {": tìm thấy {0} mục, đã xóa {1}, lỗi {2}, còn {3} mục chờ duyệt.",": found {0} items, deleted {1}, {2} errors, {3} still awaiting review."},
   {"Chọn một dòng ứng dụng trước.","Select an application row first."},{"Chưa có lịch sử. Hãy chọn ứng dụng và quét hoặc gỡ trước.","No history yet. Select an application and scan or uninstall it first."},
   {"Đang quét {0} ứng dụng…","Scanning {0} applications…"},{"Tìm thấy {0} mục cần duyệt. Không tìm thấy không có nghĩa đã sạch toàn bộ.","Found {0} items to review. Finding nothing does not mean everything is clean."},
   {"Tìm thấy: {0} mục  •  Đã chọn: {1}  •  Xóa sẽ lưu bản khôi phục trước.","Found: {0} items  •  Selected: {1}  •  Deleting saves a recovery copy first."},
   {"CHỈ XEM • ","VIEW ONLY • "},{"CHỈ XEM: ","VIEW ONLY: "},{"Chỉ xem","View only"},{"Thư mục","Folder"},{"Giá trị Registry","Registry value"},{"Khóa Registry","Registry key"},{"Rác","Junk"},{"Bản trùng","Duplicate"},{"AppCare (cũ)","AppCare (legacy)"},
   {"Chọn một mục để xem.","Select an item to inspect."},{"\r\n\r\nChỉ xem: không tự xóa mục này.","\r\n\r\nView only: this item is never deleted automatically."},{"\r\n\r\nKiểm tra đúng khóa hoặc giá trị trước khi chọn dọn.","\r\n\r\nVerify the key or value before selecting it for cleanup."},{"Chi tiết mục còn sót","Leftover details"},
   {"Đánh dấu những mục đã kiểm tra và muốn dọn.","Check the items you have reviewed and want to clean."},
   {"Sao lưu và dọn {0} mục đã đánh dấu?\r\n\r\n{1}\r\n\r\nCác mục có thể chứa cài đặt, dự án hoặc dữ liệu cá nhân. Chỉ tiếp tục khi đã kiểm tra. File được chuyển vào kho nên chưa giải phóng dung lượng ổ đĩa. Registry được lưu giá trị và khóa con, không lưu quyền ACL.","Back up and clean {0} checked items?\r\n\r\n{1}\r\n\r\nItems may hold settings, projects or personal data. Continue only after reviewing them. Files move to the vault, so no disk space is freed yet. Registry keys are saved with values and subkeys, not ACL permissions."},
   {"Đang sao lưu: ","Backing up: "},{"Đã sao lưu và dọn: ","Backed up and cleaned: "},{"Giữ lại / cần kiểm tra ","Kept / needs review "},{"Mục chưa dọn xong","Item not cleaned"},{"Không hẹn xóa được ","Could not schedule deletion for "},
   {"Đã dọn và sao lưu: {0} mục file/thư mục, {1} mục Registry.","Cleaned and backed up: {0} file/folder items, {1} Registry items."},{" Hẹn xóa khi khởi động lại: {0} mục."," Scheduled for deletion at reboot: {0} items."},{" Chưa dọn: {0} mục. Còn hiển thị: {1} mục."," Not cleaned: {0} items. Still listed: {1} items."},
   {"\r\n\r\nCó thể khôi phục trong Kho khôi phục. File trong kho vẫn chiếm dung lượng.","\r\n\r\nYou can restore them from the Recovery Vault. Files in the vault still use disk space."},{"Kết quả dọn","Cleanup result"},
   {"Chọn một bản sao lưu.","Select a backup."},{"Mục này đã khôi phục.","This item has already been restored."},
   {"Khôi phục về vị trí gốc?\r\n{0}\r\n\r\nKhông ghi đè nếu đích đã tồn tại. Nếu lần dọn trước bị gián đoạn, kiểm tra cả vị trí gốc và kho.","Restore to the original location?\r\n{0}\r\n\r\nExisting targets are never overwritten. If the previous cleanup was interrupted, check both the original location and the vault."},
   {"Đã khôi phục: ","Restored: "},{"Đánh dấu (tick) các bản sao lưu muốn xóa vĩnh viễn.","Check (tick) the backups to delete permanently."},{"đã đánh dấu","checked"},{"Kho trống.","The vault is empty."},
   {"Không có bản sao lưu nào đủ tuổi theo lựa chọn.","No backup is old enough for the chosen age."},{"cũ hơn {0} ngày","older than {0} days"},
   {"XÓA VĨNH VIỄN {0} bản sao lưu {1} ({2})?\r\n\r\n{3}","PERMANENTLY DELETE {0} backups {1} ({2})?\r\n\r\n{3}"},{"\r\n… và {0} mục khác","\r\n… and {0} more"},
   {"\r\n\r\nCẢNH BÁO: {0} bản chưa khôi phục sẽ mất vĩnh viễn — không thể hoàn tác các lần dọn tương ứng nữa.","\r\n\r\nWARNING: {0} unrestored backups will be lost forever — the corresponding cleanups can no longer be undone."},{"\r\n\r\nThao tác này không thể hoàn tác.","\r\n\r\nThis cannot be undone."},
   {"Đã xóa vĩnh viễn bản sao lưu {0} ({1}).","Permanently deleted backup {0} ({1})."},{"Không xóa được {0}: {1}","Could not delete {0}: {1}"},{"Đã xóa vĩnh viễn {0} bản sao lưu, giải phóng {1}. Lỗi: {2}.","Permanently deleted {0} backups, freed {1}. Errors: {2}."},{"Kết quả dọn kho","Vault purge result"},
   {"Đã xuất danh sách: ","List exported: "},{"Đã xuất báo cáo: ","Report exported: "},
   // Leftover scan window (ScanWindow.cs)
   {"Quét phần còn sót","Leftover scan"},{"Quét sâu","Deep scan"},{"Quét nhanh","Quick scan"},{"Quét sâu: ","Deep scan: "},{"Quét nhanh: ","Quick scan: "},{"Đang chuẩn bị quét…","Preparing scan…"},
   {"Đang sao lưu và xóa. Hãy chờ thao tác hoàn tất.","Backing up and deleting. Please wait for the operation to finish."},
   {"Còn {0} ghi chú được rút gọn.","{0} more notes were truncated."},{"LỖI quét: ","Scan ERROR: "},{"Đang tính dung lượng các mục tìm thấy…","Measuring the size of found items…"},
   {"{0} thư mục đã duyệt  •  {1} ghi chú (xem Nhật ký)","{0} folders visited  •  {1} notes (see Log)"},{"{0} thư mục đã duyệt  •  {1} mục tìm thấy","{0} folders visited  •  {1} items found"},
   {"Cửa sổ quét: {0} mục, {1} thư mục đã duyệt, {2} ghi chú.","Scan window: {0} items, {1} folders visited, {2} notes."},{"Chờ duyệt","Awaiting review"},
   {"Hãy đánh dấu những mục đã kiểm tra và muốn xóa.","Check the items you have reviewed and want to delete."},
   {"Sao lưu và xóa {0} mục đã chọn{1}?\r\n\r\n{2}\r\n\r\nFile và thư mục được chuyển vào Kho khôi phục trên cùng ổ đĩa. Registry được lưu giá trị và khóa con trước khi xóa.","Back up and delete {0} selected items{1}?\r\n\r\n{2}\r\n\r\nFiles and folders move to the Recovery Vault on the same drive. Registry keys are saved with values and subkeys before deletion."},
   {" (khoảng {0})"," (about {0})"},{"Xác nhận xóa","Confirm deletion"},{"Đang sao lưu và xóa {0}/{1}","Backing up and deleting {0}/{1}"},{"Đã xóa (có sao lưu)","Deleted (backed up)"},{"Đã sao lưu và xóa: ","Backed up and deleted: "},{"Giữ lại ","Kept "},
   {"Hoàn tất xóa.  Còn {0} mục chờ duyệt.","Deletion finished.  {0} items still await review."},{"Đã xóa {0} mục và lưu bản khôi phục","Deleted {0} items and saved recovery copies"},
   {"; {0} mục chưa xóa được — di chuột lên dòng màu đỏ để xem lý do.","; {0} items could not be deleted — hover a red row for the reason."},{" Có thể khôi phục trong tab Kho khôi phục."," You can restore them in the Recovery Vault tab."},
   {"Không hoàn tất quét.\r\n{0}\r\n\r\nĐóng cửa sổ rồi quét lại từ tab Phần còn sót.","Scan not completed.\r\n{0}\r\n\r\nClose this window and scan again from the Leftovers tab."},{"Lỗi không xác định.","Unknown error."},{"Không hoàn tất quét: ","Scan not completed: "},
   {"Chưa tìm thấy mục nào trước khi dừng.\r\nCó thể quét lại từ tab Phần còn sót.","Nothing was found before the scan stopped.\r\nYou can scan again from the Leftovers tab."},
   {"Không tìm thấy phần còn sót theo các quy tắc hiện tại.\r\nĐiều này không bảo đảm hệ thống đã sạch hoàn toàn.","No leftovers found with the current rules.\r\nThis does not guarantee the system is completely clean."},
   {"Quét gặp lỗi: {0}. Kết quả bên dưới có thể chưa đầy đủ.","The scan hit an error: {0}. The results below may be incomplete."},
   {"Ứng dụng vẫn còn đăng ký cài đặt nên chỉ có thể xem. Hãy gỡ chính thức rồi quét lại để dọn.","The application is still registered as installed, so this list is view-only. Uninstall it officially, then scan again to clean."},{" Quét có thể chưa đầy đủ."," The scan may be incomplete."},
   {"Không hoàn tất quét.","Scan not completed."},{"Đã dừng quét — kết quả có thể chưa đầy đủ.","Scan stopped — results may be incomplete."},{"Hoàn tất quét.","Scan complete."},{"  Tìm thấy {0} mục.","  Found {0} items."},
   {"Quét chưa đầy đủ: đã dừng và một số thư mục hoặc khóa không đọc được vì thiếu quyền. Kết quả bên dưới vẫn có thể duyệt. Chạy lại với quyền quản trị (cùng tài khoản Windows) nếu cần.","Incomplete scan: it was stopped and some folders or keys could not be read for lack of permission. The results below can still be reviewed. Run again as administrator (same Windows account) if needed."},
   {"Quét đã dừng. Kết quả có thể chưa đầy đủ. Có thể quét lại từ tab Phần còn sót.","Scan stopped. Results may be incomplete. You can scan again from the Leftovers tab."},
   {"Quét chưa đầy đủ: một số thư mục hoặc khóa Registry không đọc được vì thiếu quyền. Kết quả bên dưới vẫn có thể duyệt. Chạy lại với quyền quản trị (cùng tài khoản Windows) nếu cần.","Incomplete scan: some folders or Registry keys could not be read for lack of permission. The results below can still be reviewed. Run again as administrator (same Windows account) if needed."},
   {"Bỏ qua tính dung lượng","Skip size measurement"},{"Tìm thấy {0} mục","Found {0} items"},{"  •  Đã chọn {0}","  •  Selected {0}"},{"  •  Đã xóa {0}, lỗi {1}","  •  Deleted {0}, {1} errors"},
   // Startup and Windows Tools tabs (AdvancedUI.cs, Advanced.cs catalog/state strings)
   {"Có sẵn","Available"},{"Không có sẵn","Not available"},{"\r\nCông cụ không có trên phiên bản Windows này.","\r\nThis tool is not present on this Windows edition."},{"Chọn công cụ muốn mở.","Select the tool to open."},{"\r\nTiếp tục mở công cụ với quyền quản trị?","\r\nOpen this tool with administrator rights?"},
   {"Chọn một mục khởi động.","Select a startup entry."},{"Có đăng ký","Registered"},{"Đã tắt bằng Tweek Pro","Disabled by Tweek Pro"},{"Kho Tweek Pro","Tweek Pro vault"},
   {"Đang đọc mục khởi động…","Reading startup entries…"},{"Đã đọc {0} mục khởi động và bản đã tắt. Chưa gồm service/driver/tác vụ lịch.","Read {0} startup entries and disabled copies. Services/drivers/scheduled tasks are not included."},
   {"Mục này đã nằm trong kho; dùng Bật lại từ kho.","This entry is already in the vault; use Re-enable from vault."},
   {"Tắt mục khởi động này và lưu bản khôi phục?\r\n\r\n{0}\r\n{1}\r\n\r\nKhông dừng ứng dụng đang chạy. Thay đổi áp dụng cho lần đăng nhập sau.","Disable this startup entry and save a recovery copy?\r\n\r\n{0}\r\n{1}\r\n\r\nRunning applications are not stopped. The change applies at the next sign-in."},
   {"Đã tắt và sao lưu: ","Disabled and backed up: "},{"Mục này vẫn có đăng ký. Nếu bị Windows tắt, hãy dùng Startup của Windows.","This entry is still registered. If Windows disabled it, use Windows Startup."},
   {"Khôi phục mục khởi động {0}?\r\nKhông ghi đè mục đã tồn tại. Windows vẫn có thể chặn theo cài đặt Startup riêng.","Restore startup entry {0}?\r\nExisting entries are not overwritten. Windows may still block it through its own Startup settings."},
   {"Đã khôi phục đăng ký khởi động: ","Startup registration restored: "},{"Đã xuất mục khởi động.","Startup entries exported."},
   {"Chọn ứng dụng ở tab Ứng dụng rồi Quét mục đang xem để ghi nhận trước; sau đó dùng Quét siêu sâu.","Select an application in the Applications tab and use Scan selected first; then use Deep scan."},
   {"Quét sâu: {0} — có thể dừng bằng nút Dừng quét sâu.","Deep scan: {0} — use Stop deep scan to cancel."},{"Còn {0} ghi chú được rút gọn trong nhật ký.","{0} more notes were truncated in the log."},
   {"Quét sâu xong: {0} mục; {1} ghi chú về phạm vi/đường dẫn bỏ qua. Xem Nhật ký; không bảo đảm mọi dấu vết đã được tìm thấy.","Deep scan done: {0} items; {1} notes about skipped scopes/paths. See the Log; not every trace is guaranteed to be found."},
   {"Đã dừng quét. Giữ kết quả các ứng dụng đã quét xong; ứng dụng đang quét chưa được cộng vào.","Scan stopped. Results of fully scanned applications are kept; the application being scanned was not added."},
   {"Mở trình khôi phục hệ thống; bạn chọn điểm khôi phục trong Windows.","Opens System Restore; you pick the restore point in Windows."},{"Thông số hệ thống và biến môi trường.","System properties and environment variables."},{"Thuộc tính hệ thống, tên máy và điểm khôi phục.","System properties, computer name and restore points."},{"Thông tin phần cứng và phần mềm.","Hardware and software information."},
   {"Kết nối mạng và adapter.","Network connections and adapters."},{"Trung tâm bảo mật / trạng thái bảo vệ Windows.","Security Center / Windows protection status."},
   {"Tiến trình, hiệu năng và ứng dụng khởi động.","Processes, performance and startup apps."},{"Quản lý dịch vụ.","Manage services."},{"Quản lý tác vụ theo lịch.","Manage scheduled tasks."},{"Quản lý thiết bị và driver.","Manage devices and drivers."},{"Xem nhật ký Windows.","View Windows event logs."},
   {"Quản lý phân vùng và ổ đĩa.","Manage partitions and disks."},{"Quản lý thư mục chia sẻ.","Manage shared folders."},{"Chính sách nhóm; có thể không có trên Windows Home.","Group Policy; may be missing on Windows Home."},{"Bật/tắt thành phần Windows.","Turn Windows features on or off."},
   {"Mở công cụ tối ưu ổ đĩa.","Opens the drive optimizer."},{"Xem tài nguyên CPU, RAM, đĩa và mạng.","View CPU, RAM, disk and network usage."},{"Bàn phím trên màn hình.","On-screen keyboard."},{"Sao lưu và khôi phục Windows.","Windows Backup and Restore."},{"Công cụ gỡ phần mềm độc hại của Microsoft.","Microsoft Malicious Software Removal Tool."},
   {"Hiển thị cấu hình mạng; không thay đổi mạng.","Shows the network configuration; changes nothing."},{"Liệt kê kết nối TCP/IP và tiến trình sở hữu.","Lists TCP/IP connections and owning processes."},
   {"Kiểm tra ổ đĩa; sửa lỗi cần quyền quản trị và có thể yêu cầu khởi động lại.","Checks the disk; repairs need administrator rights and may require a reboot."},
   {"Kiểm tra và sửa file hệ thống; cần quyền quản trị.","Checks and repairs system files; requires administrator rights."},{"Mở cài đặt bảo mật Windows.","Opens Windows Security settings."},{"Xem trạng thái bật/tắt khởi động do Windows quản lý.","View the startup on/off state managed by Windows."},
   // Network tab runtime texts (NetworkUI.cs)
   {"Mạng: đã dừng phiên ETW {0}.","Network: stopped ETW session {0}."},{"Không bật được ETW: ","Could not start ETW: "},{"Mạng: đã bật phiên ETW {0} (kernel TCP/IP, chỉ đọc).","Network: started ETW session {0} (kernel TCP/IP, read-only)."},
   {"Mạng: phiên ETW dừng — ","Network: ETW session stopped — "},{"Mạng: {0} kết nối, {1} tiến trình.","Network: {0} connections, {1} processes."},{"Không đọc được bảng kết nối.\r\n","Could not read the connection table.\r\n"},
   {"Đã gửi: {0}  •  Đã nhận: {1} (từ khi bật ETW, toàn tiến trình)","Sent: {0}  •  Received: {1} (since ETW started, whole process)"},{"Chi tiết kết nối","Connection details"},{"Đã xuất bảng kết nối: ","Connection table exported: "},
   // Empty folders tab (EmptyFolderUI.cs)
   {"Thư mục quét: ","Scan folder: "},{"(chưa chọn)","(not chosen)"},{"Chọn thư mục để tìm thư mục rỗng","Choose a folder to search for empty folders"},
   {"{0} nhánh thư mục rỗng  •  Đã chọn {1}","{0} empty folder branches  •  Selected {1}"},{"  •  (chưa đủ — đã chạm giới hạn)","  •  (partial — limit reached)"},{"  •  Nhấp đúp để mở vị trí.","  •  Double-click to open the location."},{"  •  (chưa đủ)","  •  (partial)"},
   {"Chọn một thư mục để quét trước.","Choose a folder to scan first."},{"Đang quét…","Scanning…"},{"Đang quét","Scanning"},{"Đã dừng quét.","Scan stopped."},{"Đang xóa…","Deleting…"},{"Đã dừng xóa.","Deletion stopped."},{"Chọn một thư mục.","Select a folder."},
   {"Thư mục rỗng: đang quét (chỉ đọc) {0}.","Empty folders: scanning (read-only) {0}."},{"Quét xong: {0} nhánh rỗng trong {1} thư mục đã duyệt","Scan done: {0} empty branches in {1} folders visited"},{"Thư mục rỗng: tìm thấy {0} nhánh rỗng.","Empty folders: found {0} empty branches."},
   {"Quét rồi đánh dấu thư mục rỗng muốn xóa.","Scan first, then check the empty folders to delete."},
   {"Xóa {0} nhánh thư mục rỗng?\r\n\r\n{1}\r\n\r\nCác thư mục này không chứa tệp nào. Thao tác xóa thẳng (không sao lưu vì không có dữ liệu); Windows/ứng dụng có thể tự tạo lại khi cần.","Delete {0} empty folder branches?\r\n\r\n{1}\r\n\r\nThese folders contain no files. They are deleted directly (no backup, since there is no data); Windows/applications may recreate them when needed."},
   {"Đã xóa {0} nhánh thư mục rỗng. Bỏ qua: {1}. Lỗi: {2}.","Deleted {0} empty folder branches. Skipped: {1}. Errors: {2}."},{"Thư mục rỗng: ","Empty folders: "},{"Thư mục rỗng lỗi: ","Empty folders error: "},{"Kết quả dọn thư mục rỗng","Empty folder cleanup result"},
   // Disk analyzer tab (DiskAnalyzerUI.cs, DiskAnalyzer.cs stage)
   {"Thư mục phân tích: ","Analyzed folder: "},{"Chọn thư mục để phân tích dung lượng","Choose a folder to analyze disk usage"},{"{0} trong {1} tệp, {2} thư mục con","{0} in {1} files, {2} subfolders"},{"  •  Nhấp đúp một dòng để mở vị trí.","  •  Double-click a row to open its location."},
   {"Chọn một thư mục để phân tích trước.","Choose a folder to analyze first."},{"Đang phân tích…","Analyzing…"},{"Đang phân tích","Analyzing"},{"Đã dừng phân tích.","Analysis stopped."},
   {"Phân tích ổ đĩa: đang quét (chỉ đọc) {0}.","Disk analyzer: scanning (read-only) {0}."},{"Xong: {0} trong {1} tệp","Done: {0} in {1} files"},{"Phân tích ổ đĩa: {0}, {1} tệp, {2} nhóm thư mục.","Disk analyzer: {0}, {1} files, {2} folder groups."},
   {"{0} tệp","{0} files"},{"Thư mục con nặng nhất","Heaviest subfolders"},{"Tổng dung lượng của các tệp ","Total size of files "},{"Dung lượng theo phần mở rộng","Size by extension"},{"Tệp lớn nhất","Largest files"},
   {"Chọn một dòng thư mục hoặc tệp.","Select a folder or file row."},{"Dòng theo phần mở rộng không có vị trí cụ thể để mở.","Extension rows have no specific location to open."},{"Chưa có kết quả để xuất. Hãy Phân tích trước.","No results to export yet. Run Analyze first."},{"Đã xuất phân tích ổ đĩa: ","Disk analysis exported: "},
   // Duplicates tab (DuplicateUI.cs, DuplicateFinder.cs stages)
   {"Chọn thư mục để tìm tệp trùng lặp","Choose a folder to search for duplicate files"},{"Giữ lại: {0}\r\nSố bản: {1}\r\nTiết kiệm nếu dọn: {2}","Kept: {0}\r\nCopies: {1}\r\nReclaimable if cleaned: {2}"},
   {"{0} nhóm trùng lặp  •  Đã chọn {1} nhóm, {2} bản dư, giải phóng ~{3}","{0} duplicate groups  •  Selected {1} groups, {2} redundant copies, ~{3} reclaimable"},{"  •  Chuyển vào Kho: chưa giải phóng cho đến khi xóa vĩnh viễn","  •  Move to Vault: space is freed only after permanent deletion"},
   {"Xóa thẳng bản trùng đã chọn","Delete selected duplicates directly"},{"Dọn bản trùng đã chọn (vào kho)","Clean selected duplicates (to vault)"},
   {"Tìm trùng lặp: đang quét (chỉ đọc) {0}.","Duplicates: scanning (read-only) {0}."},{"Quét xong: {0} nhóm trùng, {1} tệp đã duyệt, tiết kiệm tối đa {2}","Scan done: {0} duplicate groups, {1} files visited, up to {2} reclaimable"},{"Tìm trùng lặp: {0} nhóm, có thể giải phóng {1}.","Duplicates: {0} groups, {1} reclaimable."},
   {"Không tìm thấy tệp trùng lặp trong thư mục này (ngưỡng tối thiểu {0} KB).","No duplicate files found in this folder (minimum size {0} KB)."},{"Đang so khớp nội dung","Comparing content"},{"Đang chuyển vào kho","Moving to vault"},{"Đang xóa thẳng","Deleting directly"},
   {"Quét rồi đánh dấu nhóm muốn dọn.","Scan first, then check the groups to clean."},{"• Giữ {0} — bỏ {1} bản ({2})","• Keep {0} — remove {1} copies ({2})"},
   {"XÓA THẲNG {0} bản trùng ({1}) mà KHÔNG lưu bản khôi phục?\r\n\r\n{2}\r\n\r\nBản giữ lại của mỗi nhóm vẫn được giữ. Thao tác này không thể hoàn tác.","DELETE {0} duplicate copies ({1}) DIRECTLY without a recovery copy?\r\n\r\n{2}\r\n\r\nThe kept copy of each group stays. This cannot be undone."},
   {"Xác nhận lần cuối: xóa thẳng {0} bản trùng, không có bản sao lưu?","Final confirmation: delete {0} duplicate copies directly, with no backup?"},
   {"Chuyển {0} bản trùng ({1}) vào Kho khôi phục?\r\n\r\n{2}\r\n\r\nLần dọn này tạo một bản sao lưu; có thể khôi phục hoặc xóa vĩnh viễn sau trong tab Kho khôi phục. Dung lượng ổ đĩa chưa được giải phóng cho đến khi xóa vĩnh viễn.","Move {0} duplicate copies ({1}) to the Recovery Vault?\r\n\r\n{2}\r\n\r\nThis cleanup creates one backup; you can restore or permanently delete it later in the Recovery Vault tab. Disk space is freed only after permanent deletion."},
   {"Tìm trùng lặp: bắt đầu xóa thẳng {0} bản trùng trong {1} nhóm.","Duplicates: deleting {0} copies in {1} groups directly."},{"Tìm trùng lặp: bắt đầu chuyển vào kho {0} bản trùng trong {1} nhóm.","Duplicates: moving {0} copies in {1} groups to the vault."},{"Đã dừng dọn.","Cleanup stopped."},
   {"Đã xóa thẳng {0} bản trùng ({1}). Bỏ qua vì đang dùng: {2}. Lỗi: {3}.","Deleted {0} duplicate copies directly ({1}). Skipped because in use: {2}. Errors: {3}."},{"Đã chuyển vào kho {0} bản trùng ({1}). Bỏ qua vì đang dùng: {2}. Lỗi: {3}.","Moved {0} duplicate copies to the vault ({1}). Skipped because in use: {2}. Errors: {3}."},
   {"Tìm trùng lặp: ","Duplicates: "},{"Dọn trùng lỗi: ","Duplicate cleanup error: "},{"Kết quả dọn trùng lặp","Duplicate cleanup result"},{"Chọn một nhóm để xem các bản.","Select a group to view its copies."},
   {"Các bản trùng","Duplicate copies"},{"Nhóm trùng lặp","Duplicate group"},{"{0} bản  •  {1} mỗi tệp  •  tiết kiệm {2}","{0} copies  •  {1} each  •  {2} reclaimable"},{"Vai trò","Role"},{"Giữ lại","Kept"},{"Trùng","Duplicate"},
  };
 }
}
