using System;
using System.Collections.Generic;

namespace TweekPro.Explorer {
 /// <summary>English strings for the Explorer tab (switches + file inspector); merged by Core.L, keys must not repeat elsewhere.</summary>
 public static class ExplorerLang {
  public static readonly Dictionary<string,string> Table=new Dictionary<string,string>(StringComparer.Ordinal){
   {"Explorer","File Explorer"},
   {"Tùy chỉnh","Setting"},{"Tùy chỉnh File Explorer","File Explorer settings"},{"Xem chi tiết tệp — kéo thả tệp vào đây hoặc dán đường dẫn","File details — drop a file here or paste a path"},
   {"Hiển thị tệp","File display"},{"Điều hướng","Navigation"},{"Thanh tác vụ","Taskbar"},
   {"Hiện phần mở rộng tệp (.exe, .pdf…)","Show file extensions (.exe, .pdf…)"},{"Luôn hiện đuôi tệp để nhận ra tệp giả dạng như \"hoadon.pdf.exe\". Nên bật.","Always show extensions so disguised files like \"invoice.pdf.exe\" stand out. Recommended."},
   {"Hiện tệp và thư mục ẩn","Show hidden files and folders"},{"Hiện các mục có thuộc tính Ẩn (AppData, cấu hình ứng dụng…) với biểu tượng mờ.","Shows items with the Hidden attribute (AppData, application settings…) with a faded icon."},
   {"Hiện tệp hệ thống được bảo vệ","Show protected operating system files"},{"Hiện cả tệp Windows đánh dấu Hệ thống (desktop.ini, pagefile.sys, thư mục Recovery…). Chỉ bật khi cần vì dễ xóa nhầm.","Also shows Windows files marked System (desktop.ini, pagefile.sys, the Recovery folder…). Enable only when needed; easy to delete by mistake."},
   {"Hiện hộp chọn để tích nhiều mục","Show item check boxes"},{"Mỗi tệp có một ô tích, chọn nhiều mục không cần giữ Ctrl (tiện với màn hình cảm ứng).","Every file gets a check box so multi-select works without Ctrl (handy on touch screens)."},
   {"Hiện thanh trạng thái","Show status bar"},{"Dòng dưới cùng của Explorer: số mục, dung lượng phần đang chọn.","Bottom line of Explorer: item count and size of the selection."},
   {"Chế độ gọn (Windows 11)","Compact view (Windows 11)"},{"Các hàng sát nhau hơn, hiện được nhiều tệp hơn trên một màn hình.","Tighter rows so more files fit on one screen."},
   {"Hiện chú giải khi trỏ vào tệp","Show pop-up description on hover"},{"Hộp thông tin nhỏ (loại, dung lượng, ngày sửa) khi rê chuột lên tệp hoặc thư mục.","Small info box (type, size, modified date) when hovering a file or folder."},
   {"Tô màu tệp nén / mã hóa NTFS","Show compressed / encrypted NTFS files in color"},{"Tên tệp nén NTFS hiện màu xanh dương, tệp mã hóa EFS màu xanh lá.","NTFS-compressed names appear blue, EFS-encrypted names green."},
   {"Hiện đường dẫn đầy đủ trên thanh tiêu đề","Display the full path in the title bar"},{"Tiêu đề cửa sổ Explorer hiện C:\\Users\\…\\Thư mục thay vì chỉ tên thư mục.","The Explorer title shows C:\\Users\\…\\Folder instead of just the folder name."},
   {"Mở Explorer vào This PC","Open File Explorer to This PC"},{"Explorer mở thẳng vào danh sách ổ đĩa thay vì Home / Quick access.","Explorer opens on the drive list instead of Home / Quick access."},
   {"Hiện tệp gần đây trong Home / Quick access","Show recently used files in Home / Quick access"},{"Tắt nếu không muốn người dùng máy nhìn thấy các tệp vừa mở.","Turn off if others using this PC should not see recently opened files."},
   {"Hiện thư mục thường dùng trong Home / Quick access","Show frequently used folders in Home / Quick access"},{"Danh sách thư mục hay mở do Windows tự đề xuất.","Folders Windows suggests because you open them often."},
   {"Hiện thông báo của nhà cung cấp đồng bộ","Show sync provider notifications"},{"Các gợi ý / quảng cáo OneDrive chen trong Explorer. Tắt để Explorer sạch hơn.","OneDrive tips / ads shown inside Explorer. Turn off for a cleaner Explorer."},
   {"Hiện giây trên đồng hồ thanh tác vụ","Show seconds in the taskbar clock"},{"Đồng hồ góc phải hiện cả giây (tốn thêm một chút pin trên laptop).","The clock in the corner also shows seconds (uses slightly more battery on laptops)."},
   {"Căn thanh tác vụ sang trái (Windows 11)","Left-align the taskbar (Windows 11)"},{"Nút Start và các icon dồn về góc trái như Windows 10.","Start button and icons move to the left corner like Windows 10."},
   {"Hiện nút Task View","Show the Task View button"},{"Nút xem mọi cửa sổ và màn hình ảo trên thanh tác vụ.","Taskbar button that shows all windows and virtual desktops."},
   {"Hiện nút Widgets (Windows 11)","Show the Widgets button (Windows 11)"},{"Bảng thời tiết / tin tức ở góc trái thanh tác vụ.","Weather / news panel at the left of the taskbar."},
   {"Áp dụng thay đổi","Apply changes"},{"Áp dụng {0} thay đổi","Apply {0} changes"},{"Đọc lại","Reload"},{"Mặc định Windows","Windows defaults"},{"Khuyến nghị an toàn","Safe recommendations"},{"Khởi động lại Explorer","Restart Explorer"},{"Mở Tùy chọn thư mục","Open Folder Options"},
   {"Tích hoặc bỏ tích rồi bấm Áp dụng thay đổi. Mỗi giá trị được ghi vào HKCU của tài khoản hiện tại và giá trị cũ lưu vào Kho khôi phục (loại Explorer) để bật lại bằng một nút. Cửa sổ Explorer đang mở tự làm mới; mục thanh tác vụ cần Khởi động lại Explorer.","Check or uncheck items, then click Apply changes. Each value is written to the current user's HKCU and the previous value is stored in the Recovery Vault (kind Explorer) so one click brings it back. Open Explorer windows refresh themselves; taskbar items need Restart Explorer."},
   {"Chỉ đọc được trên Windows; danh sách hiện giá trị mặc định.","Readable on Windows only; the list shows default values."},
   {"Mặc định (bật)","Default (on)"},{"Mặc định (tắt)","Default (off)"},{"Giá trị lạ","Unexpected value"},{"chưa có","not set"},{"bật = {0}, tắt = {1}","on = {0}, off = {1}"},
   {"{0} tùy chỉnh  •  {1} đang bật  •  {2} thay đổi chờ áp dụng","{0} settings  •  {1} on  •  {2} pending changes"},
   {"Chưa có thay đổi nào: tích hoặc bỏ tích một tùy chỉnh trước.","Nothing to apply: check or uncheck a setting first."},
   {"BẬT","ON"},{"TẮT","OFF"},{"bật","on"},{"tắt","off"},
   {"Áp dụng {0} thay đổi cho File Explorer của tài khoản hiện tại?\r\n\r\n{1}\r\n\r\nGiá trị cũ được lưu vào Kho khôi phục.","Apply {0} changes to File Explorer for the current account?\r\n\r\n{1}\r\n\r\nPrevious values are saved to the Recovery Vault."},
   {"\r\n\r\nLƯU Ý: hiện tệp hệ thống được bảo vệ làm các tệp Windows quan trọng lộ ra trong Explorer; đừng xóa hay đổi tên chúng.","\r\n\r\nNOTE: showing protected operating system files exposes important Windows files in Explorer; do not delete or rename them."},
   {"Explorer: {0} → {1}.","Explorer: {0} → {1}."},{"Đã áp dụng {0}/{1} thay đổi.","Applied {0}/{1} changes."},
   {"\r\n\r\nCửa sổ Explorer đang mở sẽ tự cập nhật; nếu chưa, bấm F5 trong Explorer.","\r\n\r\nOpen Explorer windows update themselves; if not, press F5 in Explorer."},
   {"\r\nTùy chỉnh thanh tác vụ chỉ có hiệu lực sau khi Khởi động lại Explorer.","\r\nTaskbar settings take effect only after Restart Explorer."},
   {"Tùy chỉnh Explorer","Explorer settings"},
   {"Khởi động lại Explorer?\r\n\r\nMọi cửa sổ Explorer đang mở sẽ đóng, thanh tác vụ và màn hình nền biến mất vài giây rồi hiện lại. Tệp đang sao chép trong Explorer sẽ bị ngắt.","Restart Explorer?\r\n\r\nEvery open Explorer window closes, the taskbar and desktop disappear for a few seconds and come back. File copies running in Explorer are interrupted."},
   {"Đã khởi động lại Explorer ({0} tiến trình).","Explorer restarted ({0} process(es))."},
   {"Tùy chỉnh này không nằm trong danh mục cho phép của Tweek Pro.","This setting is not in Tweek Pro's allow-list."},
   {"Giá trị cũ: {0}; khôi phục = ghi lại giá trị cũ (hoặc xóa nếu trước đó chưa có).","Previous value: {0}; restore = write the previous value back (or delete it if it did not exist)."},
   {"Không phải bản sao lưu tùy chỉnh Explorer.","Not an Explorer settings backup."},{"Bản sao lưu trỏ ra ngoài các khóa Explorer cho phép; từ chối khôi phục.","The backup points outside the allowed Explorer keys; restore refused."},{"Không đọc được giá trị cũ trong bản sao lưu.","Cannot read the previous value stored in the backup."},
   {"Không mở được hộp thoại Thuộc tính (mã {0}).","Could not open the Properties dialog (code {0})."},
   {"Chọn tệp…","Choose file…"},{"Xem chi tiết","Inspect"},{"Thuộc tính Windows","Windows Properties"},{"Tính SHA-256 / MD5","Compute SHA-256 / MD5"},
   {"Chưa có tệp nào được xem.","No file has been inspected yet."},{"Đã sao chép giá trị.","Value copied."},{"Đã sao chép báo cáo chi tiết tệp.","File details report copied."},
   {"Chưa chọn tệp.\r\nBấm Chọn tệp…, dán đường dẫn rồi Enter, hoặc kéo một tệp từ Explorer vào đây để xem loại thật, thuộc tính ẩn/hệ thống, chữ ký số, mã băm và cảnh báo giả dạng (hoadon.pdf.exe).","No file selected.\r\nClick Choose file…, paste a path and press Enter, or drag a file from Explorer here to see its real type, hidden/system attributes, digital signature, hashes and disguise warnings (invoice.pdf.exe)."},
   {"Chọn tệp để xem chi tiết","Choose a file to inspect"},{"Mọi tệp","All files"},{"Dán hoặc chọn một đường dẫn tệp trước.","Paste or choose a file path first."},
   {"Đang đọc…","Reading…"},{"Đã dừng.","Stopped."},{"{0}  •  {1}  •  {2} cảnh báo","{0}  •  {1}  •  {2} warnings"},{"Chi tiết tệp: {0} ({1}, {2} cảnh báo).","File details: {0} ({1}, {2} warnings)."},
   {"Đang đọc loại tệp…","Reading file type…"},{"Đang kiểm tra chữ ký số…","Checking digital signature…"},{"Đang băm… {0}%","Hashing… {0}%"},{"Không băm được: ","Could not hash: "},
   {"Máy này","This computer"},{"Mạng nội bộ","Local intranet"},{"Trang tin cậy","Trusted sites"},{"Internet","Internet"},{"Trang hạn chế","Restricted sites"},
   {"Đuôi kép: tệp thực thi {0} giả dạng tài liệu {1}. Không mở nếu không chắc nguồn gốc.","Double extension: executable {0} disguised as a {1} document. Do not open unless you trust the source."},
   {"Tên tệp chứa ký tự đảo chiều Unicode — phần mở rộng hiển thị có thể không phải phần mở rộng thật.","The name contains Unicode right-to-left controls — the displayed extension may not be the real one."},
   {"Tệp thực thi tải từ Internet và chưa có chữ ký số: kiểm tra nguồn trước khi chạy.","Executable downloaded from the Internet without a digital signature: verify the source before running."},
   {"Nội dung là chương trình Windows (PE {0}) dù phần mở rộng là {1}.","The content is a Windows program (PE {0}) although the extension is {1}."},{"(không có)","(none)"},
   {"Phần mở rộng {0} nhưng nội dung không phải tệp PE hợp lệ.","Extension {0} but the content is not a valid PE file."},
   {"Tải từ vùng «{0}» (Mark of the Web): Windows còn cảnh báo khi mở.","Downloaded from the «{0}» zone (Mark of the Web): Windows still warns when opening."},
   {"Thuộc tính Ẩn + Hệ thống: Explorer chỉ hiện khi bật «Hiện tệp hệ thống được bảo vệ».","Hidden + System attributes: Explorer shows it only with «Show protected operating system files» on."},
   {"Thuộc tính Ẩn: Explorer chỉ hiện khi bật «Hiện tệp và thư mục ẩn».","Hidden attribute: Explorer shows it only with «Show hidden files and folders» on."},
   {"Liên kết (symlink / junction): nội dung thật nằm ở nơi khác.","Link (symlink / junction): the real content lives elsewhere."},{"Chỉ đọc: cần bỏ thuộc tính trước khi sửa hoặc xóa.","Read-only: clear the attribute before editing or deleting."},
   {"Chữ ký số hợp lệ của {0}.","Valid digital signature by {0}."},
   {"Tệp không có phần mở rộng","File without extension"},{"Tệp {0}","{0} file"},{"không có phần mở rộng","no extension"},
   {"Cảnh báo an toàn","Safety warnings"},{"Ghi chú","Note"},{"Chung","General"},{"Thời gian","Timestamps"},{"Phiên bản tệp","File version"},{"Mã băm","Hashes"},
   {"Tên","Name"},{"Thuộc tính","Attributes"},{"Giá trị","Value"},{"Kiến trúc","Architecture"},{"Tạo","Created"},{"Truy cập lần cuối","Last accessed"},{"Chủ sở hữu","Owner"},{"Nguồn tải","Download source"},{"từ","from"},{"Không có dấu tải từ Internet","No Internet download mark"},{"không áp dụng","not applicable"},
   {"Sản phẩm","Product"},{"Công ty","Company"},{"Bỏ qua: tệp lớn hơn 2 GB.","Skipped: file larger than 2 GB."},
   {"Ẩn","Hidden"},{"Chỉ đọc","Read-only"},{"Liên kết","Link"},{"Nén NTFS","NTFS compressed"},{"Mã hóa EFS","EFS encrypted"},{"Lưu trữ","Archive"},{"Tạm","Temporary"},{"Ngoại tuyến","Offline"},{"Bình thường","Normal"},
   {"Chi tiết tệp","File details"}
  };
 }
}
